using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.Shapes;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Styling;

namespace XYUI.Avalonia.Controls;

public static partial class XyuiComponentStyles
{
    static void Batch05(Styles styles)
    {
        var bar = new Style(x => x.OfType<XYCommandBar>().Class("xyui-command-bar")); Brush(bar, Border.BackgroundProperty, "XY.Brush.Surface.App"); bar.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(0))); styles.Add(bar);
        var barSurface = new Style(x => x.OfType<Border>().Class("xyui-command-bar-surface")); Brush(barSurface, Border.BackgroundProperty, "XY.Brush.Surface.Toolbar"); Brush(barSurface, Border.BorderBrushProperty, "XY.Brush.Border.Color.Default"); barSurface.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(1))); styles.Add(barSurface);
        var command = new Style(x => x.OfType<XYCommandItem>().Class("xyui-command-item")); command.Setters.Add(new Setter(Button.HeightProperty, 28d)); command.Setters.Add(new Setter(Button.PaddingProperty, new Thickness(8, 0))); command.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 12.5d)); styles.Add(command);
        var label = new Style(x => x.OfType<TextBlock>().Class("xyui-command-label")); label.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 12.5d)); label.Setters.Add(new Setter(TextBlock.LineHeightProperty, 28d)); label.Setters.Add(new Setter(TextBlock.VerticalAlignmentProperty, VerticalAlignment.Center)); styles.Add(label);
        var context = new Style(x => x.OfType<TextBlock>().Class("xyui-command-context")); context.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 10.5d)); context.Setters.Add(new Setter(TextBlock.LineHeightProperty, 28d)); context.Setters.Add(new Setter(TextBlock.VerticalAlignmentProperty, VerticalAlignment.Center)); Brush(context, TextBlock.ForegroundProperty, "XY.Brush.Text.Secondary"); styles.Add(context);
        var contextName = new Style(x => x.OfType<TextBlock>().Class("xyui-command-context-name")); contextName.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 12.5d)); contextName.Setters.Add(new Setter(TextBlock.LineHeightProperty, 28d)); contextName.Setters.Add(new Setter(TextBlock.VerticalAlignmentProperty, VerticalAlignment.Center)); contextName.Setters.Add(new Setter(TemplatedControl.FontWeightProperty, FontWeight.SemiBold)); styles.Add(contextName);
        var primary = new Style(x => x.OfType<XYCommandItem>().Class("xyui-command-primary")); Brush(primary, Button.BackgroundProperty, "XY.Brush.Surface.Toolbar"); Brush(primary, Button.ForegroundProperty, "XY.Brush.Text.Primary"); primary.Setters.Add(new Setter(Button.CornerRadiusProperty, new CornerRadius(3))); styles.Add(primary);
        var primaryIcon = new Style(x => x.OfType<XYCommandItem>().Class("xyui-command-primary").Descendant().OfType<XYIcon>()); Brush(primaryIcon, XYIcon.StrokeProperty, "XY.Brush.Text.Primary"); styles.Add(primaryIcon);
        var danger = new Style(x => x.OfType<XYCommandItem>().Class("xyui-command-danger")); danger.Setters.Add(new Setter(Button.BackgroundProperty, Brushes.Transparent)); Brush(danger, Button.ForegroundProperty, "XY.Brush.Semantic.Error.Text"); styles.Add(danger);
        var commandSelected = new Style(x => x.OfType<XYCommandItem>().Class("xyui-command-selected")); Brush(commandSelected, Button.BackgroundProperty, "XY.Brush.Surface.Selected"); Brush(commandSelected, Button.BorderBrushProperty, "XY.Brush.Border.Color.Selected"); Brush(commandSelected, Button.ForegroundProperty, "XY.Brush.Accent.Strong"); styles.Add(commandSelected);
        var commandSelectedIcon = new Style(x => x.OfType<XYCommandItem>().Class("xyui-command-selected").Descendant().OfType<XYIcon>()); Brush(commandSelectedIcon, XYIcon.StrokeProperty, "XY.Brush.Accent.Strong"); styles.Add(commandSelectedIcon);
        var divider = new Style(x => x.OfType<Border>().Class("xyui-command-divider")); divider.Setters.Add(new Setter(Border.WidthProperty, 1d)); divider.Setters.Add(new Setter(Border.HeightProperty, 20d)); divider.Setters.Add(new Setter(Border.VerticalAlignmentProperty, VerticalAlignment.Center)); Brush(divider, Border.BackgroundProperty, "XY.Brush.Border.Color.Subtle"); styles.Add(divider);
        var more = new Style(x => x.OfType<XYIconButton>().Class("xyui-command-more")); Brush(more, Button.BackgroundProperty, "XY.Brush.Surface.PanelAlt"); more.Setters.Add(new Setter(Button.WidthProperty, 28d)); more.Setters.Add(new Setter(Button.HeightProperty, 28d)); more.Setters.Add(new Setter(Button.CornerRadiusProperty, new CornerRadius(3))); more.Setters.Add(new Setter(Button.PaddingProperty, new Thickness(0))); styles.Add(more);
        var feedback = new Style(x => x.OfType<TextBlock>().Class("xyui-command-feedback")); feedback.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 11d)); feedback.Setters.Add(new Setter(TemplatedControl.FontWeightProperty, FontWeight.Normal)); feedback.Setters.Add(new Setter(TextBlock.VerticalAlignmentProperty, VerticalAlignment.Center)); Brush(feedback, TextBlock.ForegroundProperty, "XY.Brush.Text.Secondary"); styles.Add(feedback);
        var palette = new Style(x => x.OfType<XYCommandPalette>().Class("xyui-command-palette")); Brush(palette, Border.BackgroundProperty, "XY.Brush.Surface.Overlay"); Brush(palette, Border.BorderBrushProperty, "XY.Brush.Border.Color.Subtle"); palette.Setters.Add(new Setter(Border.WidthProperty, 440d)); palette.Setters.Add(new Setter(Border.MinHeightProperty, 210d)); palette.Setters.Add(new Setter(Border.MaxHeightProperty, 320d)); palette.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(10))); palette.Setters.Add(new Setter(Border.CornerRadiusProperty, new CornerRadius(5))); styles.Add(palette);
        var paletteSurface = new Style(x => x.OfType<Border>().Class("xyui-palette-surface")); Brush(paletteSurface, Border.BackgroundProperty, "XY.Brush.Surface.Overlay"); Brush(paletteSurface, Border.BorderBrushProperty, "XY.Brush.Border.Color.Subtle"); paletteSurface.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(1))); paletteSurface.Setters.Add(new Setter(Border.CornerRadiusProperty, new CornerRadius(5))); styles.Add(paletteSurface);
        var result = new Style(x => x.OfType<XYCommandPaletteItem>().Class("xyui-palette-result")); result.Setters.Add(new Setter(Border.BackgroundProperty, Brushes.Transparent)); result.Setters.Add(new Setter(Border.HeightProperty, 30d)); result.Setters.Add(new Setter(Border.HorizontalAlignmentProperty, HorizontalAlignment.Stretch)); result.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(10, 0))); result.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(0))); styles.Add(result);
        var resultLabel = new Style(x => x.OfType<TextBlock>().Class("xyui-palette-result-label")); resultLabel.Setters.Add(new Setter(TextBlock.VerticalAlignmentProperty, VerticalAlignment.Center)); styles.Add(resultLabel);
        var resultHover = new Style(x => x.OfType<XYCommandPaletteItem>().Class("xyui-palette-result-hover")); Brush(resultHover, Border.BackgroundProperty, "XY.Brush.State.Color.Hover"); styles.Add(resultHover);
        var selected = new Style(x => x.OfType<XYCommandPaletteItem>().Class("xyui-palette-result-selected")); Brush(selected, Border.BackgroundProperty, "XY.Brush.Surface.Selected"); Brush(selected, Border.BorderBrushProperty, "XY.Brush.Border.Color.Selected"); styles.Add(selected);
        var selectedLabel = new Style(x => x.OfType<XYCommandPaletteItem>().Class("xyui-palette-result-selected").Descendant().OfType<TextBlock>().Class("xyui-palette-result-label")); Brush(selectedLabel, TextBlock.ForegroundProperty, "XY.Brush.Accent.Strong"); styles.Add(selectedLabel);
        var detailLine = new Style(x => x.OfType<TextBlock>().Class("xyui-palette-detail-line")); detailLine.Setters.Add(new Setter(TextBlock.VerticalAlignmentProperty, VerticalAlignment.Center)); detailLine.Setters.Add(new Setter(TextBlock.LineHeightProperty, 20d)); styles.Add(detailLine);
        var back = new Style(x => x.OfType<XYBackForwardNavigation>().Class("xyui-back-forward")); back.Setters.Add(new Setter(Border.HeightProperty, 34d)); back.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(0))); styles.Add(back);
        var action = new Style(x => x.OfType<XYIconButton>().Class("xyui-back-forward-action")); action.Setters.Add(new Setter(Button.WidthProperty, 28d)); action.Setters.Add(new Setter(Button.HeightProperty, 28d)); action.Setters.Add(new Setter(Button.PaddingProperty, new Thickness(0))); styles.Add(action);
        var backSurface = new Style(x => x.OfType<Border>().Class("xyui-back-forward-surface")); Brush(backSurface, Border.BackgroundProperty, "XY.Brush.Surface.Panel"); Brush(backSurface, Border.BorderBrushProperty, "XY.Brush.Border.Color.Default"); backSurface.Setters.Add(new Setter(Border.HeightProperty, 34d)); backSurface.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(1))); styles.Add(backSurface);
        var locationTitle = new Style(x => x.OfType<TextBlock>().Class("xyui-location-title")); locationTitle.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 9.5d)); locationTitle.Setters.Add(new Setter(TextBlock.LineHeightProperty, 12d)); Brush(locationTitle, TextBlock.ForegroundProperty, "XY.Brush.Text.Secondary"); styles.Add(locationTitle);
        var locationText = new Style(x => x.OfType<TextBlock>().Class("xyui-location-text")); locationText.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 12.5d)); locationText.Setters.Add(new Setter(TextBlock.LineHeightProperty, 15d)); Brush(locationText, TextBlock.ForegroundProperty, "XY.Brush.Text.Primary"); styles.Add(locationText);
        var locationDivider = new Style(x => x.OfType<Border>().Class("xyui-back-forward-divider")); locationDivider.Setters.Add(new Setter(Border.VerticalAlignmentProperty, VerticalAlignment.Center)); Brush(locationDivider, Border.BackgroundProperty, "XY.Brush.Border.Color.Subtle"); styles.Add(locationDivider);
        var workspace = new Style(x => x.OfType<XYWorkspaceSwitcher>().Class("xyui-workspace-switcher")); workspace.Setters.Add(new Setter(Border.WidthProperty, 224d)); styles.Add(workspace);
        var trigger = new Style(x => x.OfType<XYButton>().Class("xyui-workspace-trigger")); trigger.Setters.Add(new Setter(TemplatedControl.TemplateProperty, XyuiButtonChrome.Create<XYButton>(HorizontalAlignment.Stretch))); trigger.Setters.Add(new Setter(Button.HeightProperty, 34d)); trigger.Setters.Add(new Setter(Button.HorizontalAlignmentProperty, HorizontalAlignment.Stretch)); trigger.Setters.Add(new Setter(Button.HorizontalContentAlignmentProperty, HorizontalAlignment.Stretch)); trigger.Setters.Add(new Setter(Button.PaddingProperty, new Thickness(10, 0, 0, 0))); trigger.Setters.Add(new Setter(Button.CornerRadiusProperty, new CornerRadius(3))); styles.Add(trigger);
        var triggerSecondary = new Style(x => x.OfType<TextBlock>().Class("xyui-workspace-secondary")); triggerSecondary.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 10.5d)); Brush(triggerSecondary, TextBlock.ForegroundProperty, "XY.Brush.Text.Secondary"); styles.Add(triggerSecondary);
        var triggerCurrent = new Style(x => x.OfType<TextBlock>().Class("xyui-workspace-current")); triggerCurrent.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 12.5d)); triggerCurrent.Setters.Add(new Setter(TemplatedControl.FontWeightProperty, FontWeight.SemiBold)); Brush(triggerCurrent, TextBlock.ForegroundProperty, "XY.Brush.Text.Primary"); styles.Add(triggerCurrent);
        var workspaceMenu = new Style(x => x.OfType<XYMenu>().Class("xyui-workspace-menu")); Brush(workspaceMenu, Border.BackgroundProperty, "XY.Brush.Surface.Overlay"); Brush(workspaceMenu, Border.BorderBrushProperty, "XY.Brush.Border.Color.Subtle"); workspaceMenu.Setters.Add(new Setter(Border.WidthProperty, 224d)); workspaceMenu.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(8))); workspaceMenu.Setters.Add(new Setter(Border.CornerRadiusProperty, new CornerRadius(4))); styles.Add(workspaceMenu);
        var workspaceItem = new Style(x => x.OfType<XYMenuItem>().Class("xyui-workspace-item")); workspaceItem.Setters.Add(new Setter(Border.HeightProperty, 32d)); workspaceItem.Setters.Add(new Setter(Border.HorizontalAlignmentProperty, HorizontalAlignment.Stretch)); workspaceItem.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(10, 0))); styles.Add(workspaceItem);
        var workspaceCheck = new Style(x => x.OfType<XYMenuItem>().Class("xyui-workspace-item").Descendant().OfType<Line>().Class("xyui-menu-check-line")); Brush(workspaceCheck, Shape.StrokeProperty, "XY.Brush.Accent.Strong"); styles.Add(workspaceCheck);
        var workspaceManage = new Style(x => x.OfType<XYMenuItem>().Class("xyui-workspace-manage")); workspaceManage.Setters.Add(new Setter(Border.BackgroundProperty, Brushes.Transparent)); styles.Add(workspaceManage);
        var viewSwitcher = new Style(x => x.OfType<XYViewSwitcher>().Class("xyui-view-switcher")); Brush(viewSwitcher, Border.BackgroundProperty, "XY.Brush.Surface.Panel"); Brush(viewSwitcher, Border.BorderBrushProperty, "XY.Brush.Border.Color.Default"); viewSwitcher.Setters.Add(new Setter(Border.HeightProperty, 36d)); viewSwitcher.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(1))); viewSwitcher.Setters.Add(new Setter(Border.CornerRadiusProperty, new CornerRadius(4))); viewSwitcher.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(2, 0))); styles.Add(viewSwitcher);
        var viewSegment = new Style(x => x.OfType<XYButton>().Class("xyui-view-segment")); viewSegment.Setters.Add(new Setter(Button.HeightProperty, 30d)); viewSegment.Setters.Add(new Setter(Button.PaddingProperty, new Thickness(10, 0))); viewSegment.Setters.Add(new Setter(Button.BackgroundProperty, Brushes.Transparent)); viewSegment.Setters.Add(new Setter(Button.BorderThicknessProperty, new Thickness(0))); viewSegment.Setters.Add(new Setter(Button.CornerRadiusProperty, new CornerRadius(3))); styles.Add(viewSegment);
        var viewSelected = new Style(x => x.OfType<XYButton>().Class("xyui-view-selected")); Brush(viewSelected, Button.BackgroundProperty, "XY.Brush.Surface.Selected"); Brush(viewSelected, Button.ForegroundProperty, "XY.Brush.Accent.Strong"); styles.Add(viewSelected);
        var viewSelectedIcon = new Style(x => x.OfType<XYButton>().Class("xyui-view-selected").Descendant().OfType<XYIcon>()); Brush(viewSelectedIcon, XYIcon.StrokeProperty, "XY.Brush.Accent.Strong"); styles.Add(viewSelectedIcon);
        var viewAccent = new Style(x => x.OfType<Border>().Class("xyui-view-segment-accent")); Brush(viewAccent, Border.BackgroundProperty, "XY.Brush.Accent.Strong"); viewAccent.Setters.Add(new Setter(Border.HeightProperty, 3d)); styles.Add(viewAccent);
        var viewDropdown = new Style(x => x.OfType<XYButton>().Class("xyui-view-dropdown-trigger")); viewDropdown.Setters.Add(new Setter(Button.HeightProperty, 34d)); viewDropdown.Setters.Add(new Setter(Button.WidthProperty, 220d)); viewDropdown.Setters.Add(new Setter(Button.PaddingProperty, new Thickness(10, 0))); styles.Add(viewDropdown);
        var viewDropdownLabel = new Style(x => x.OfType<TextBlock>().Class("xyui-view-dropdown-label")); viewDropdownLabel.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 10.5d)); Brush(viewDropdownLabel, TextBlock.ForegroundProperty, "XY.Brush.Text.Secondary"); styles.Add(viewDropdownLabel);
        var viewDropdownCurrent = new Style(x => x.OfType<TextBlock>().Class("xyui-view-dropdown-current")); viewDropdownCurrent.Setters.Add(new Setter(TemplatedControl.FontSizeProperty, 12.5d)); viewDropdownCurrent.Setters.Add(new Setter(TemplatedControl.FontWeightProperty, FontWeight.SemiBold)); styles.Add(viewDropdownCurrent);
        var viewMore = new Style(x => x.OfType<XYIconButton>().Class("xyui-view-more")); viewMore.Setters.Add(new Setter(Button.WidthProperty, 30d)); viewMore.Setters.Add(new Setter(Button.HeightProperty, 30d)); viewMore.Setters.Add(new Setter(Button.PaddingProperty, new Thickness(0))); viewMore.Setters.Add(new Setter(Button.CornerRadiusProperty, new CornerRadius(3))); viewMore.Setters.Add(new Setter(Button.VerticalAlignmentProperty, VerticalAlignment.Center)); styles.Add(viewMore);
        var viewMoreDivider = new Style(x => x.OfType<Border>().Class("xyui-view-more-divider")); viewMoreDivider.Setters.Add(new Setter(Border.WidthProperty, 1d)); viewMoreDivider.Setters.Add(new Setter(Border.HeightProperty, 20d)); viewMoreDivider.Setters.Add(new Setter(Border.VerticalAlignmentProperty, VerticalAlignment.Center)); Brush(viewMoreDivider, Border.BackgroundProperty, "XY.Brush.Border.Color.Subtle"); styles.Add(viewMoreDivider);
        var viewMoreActive = new Style(x => x.OfType<XYIconButton>().Class("xyui-view-more").Class(":selected")); Brush(viewMoreActive, Button.BackgroundProperty, "XY.Brush.Surface.Selected"); Brush(viewMoreActive, Button.ForegroundProperty, "XY.Brush.Accent.Strong"); styles.Add(viewMoreActive);
        var toc = new Style(x => x.OfType<XYTableOfContents>().Class("xyui-table-of-contents")); toc.Setters.Add(new Setter(Border.MinWidthProperty, 180d)); styles.Add(toc);
        var tocChild = new Style(x => x.OfType<XYMenuItem>().Class("xyui-toc-child")); tocChild.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(24, 0, 8, 0))); styles.Add(tocChild);
        var bottom = new Style(x => x.OfType<XYBottomNavigation>().Class("xyui-bottom-navigation")); Brush(bottom, Border.BackgroundProperty, "XY.Brush.Surface.Panel"); bottom.Setters.Add(new Setter(Border.HeightProperty, 64d)); styles.Add(bottom);
        var drawer = new Style(x => x.OfType<XYNavigationDrawer>().Class("xyui-navigation-drawer")); drawer.Setters.Add(new Setter(Border.MinWidthProperty, 44d)); styles.Add(drawer);
        var drawerBackdrop = new Style(x => x.OfType<Border>().Class("xyui-navigation-drawer-backdrop")); Brush(drawerBackdrop, Border.BackgroundProperty, "XY.Brush.Surface.Overlay"); styles.Add(drawerBackdrop);
    }
}
