using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Threading;
using Avalonia.VisualTree;
using XYUI.Avalonia.Controls;

namespace XYUI.Avalonia.Tests;

[Collection("XyuiHeadless")]
public sealed class XYUI3TableOfContentsTests : IClassFixture<XyuiHeadlessFixture>
{
    readonly XyuiHeadlessFixture _fx;
    static XYTocSection[] Sections => [new("intro", "概览", 1), new("setup", "配置", 1), new("map", "地图基础", 2, "setup"), new("data", "数据集", 2, "setup"), new("api", "API", 1)];
    public XYUI3TableOfContentsTests(XyuiHeadlessFixture fx) => _fx = fx;
    [Fact] public void Desktop_has_header_without_tree_icons_and_level2_guide() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var toc = new XYTableOfContents(new XYTableOfContentsState(Sections, "data")); var window = XyuiBatchTestHost.Show(toc); Dispatcher.UIThread.RunJobs(); Assert.Contains(toc.GetVisualDescendants().OfType<TextBlock>(), x => x.Text == "本页目录"); Assert.DoesNotContain(toc.GetVisualDescendants().OfType<XYIcon>(), _ => true); Assert.Contains(toc.GetVisualDescendants().OfType<Border>(), x => x.Classes.Contains("xyui-toc-level-guide")); window.Close(); });
    [Fact] public void Current_child_marks_parent_active_and_has_left_accent() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var toc = new XYTableOfContents(new XYTableOfContentsState(Sections, "data")); var window = XyuiBatchTestHost.Show(toc); Dispatcher.UIThread.RunJobs(); var current = toc.GetVisualDescendants().OfType<XYButton>().Single(x => x.Classes.Contains("xyui-toc-current")); Assert.Contains(toc.GetVisualDescendants().OfType<XYButton>(), x => x.Classes.Contains("xyui-toc-parent-active")); Assert.Contains(current.GetVisualDescendants().OfType<Border>(), x => x.Classes.Contains("xyui-toc-current-accent") && x.IsVisible); window.Close(); });
    [Fact] public void Compact_trigger_has_path_chevron_and_popup_width() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var toc = new XYTableOfContents(new XYTableOfContentsState(Sections, "data"), XYTableOfContentsVariant.Compact); var window = XyuiBatchTestHost.Show(toc); Dispatcher.UIThread.RunJobs(); var trigger = toc.GetVisualDescendants().OfType<XYButton>().Single(); Assert.Contains(trigger.GetVisualDescendants().OfType<TextBlock>(), x => x.Text == "本页目录"); Assert.Contains(trigger.GetVisualDescendants().OfType<TextBlock>(), x => x.Text == "配置 / 数据集"); Assert.Contains(trigger.GetVisualDescendants().OfType<XYIcon>(), x => x.Icon == XYUI.Avalonia.Vector.XyuiVectorIcon.ChevronDown); toc.SelectSection("data"); trigger.RaiseEvent(new RoutedEventArgs(Button.ClickEvent)); Assert.Equal(trigger.Bounds.Width, toc.Popup.Width, 1); window.Close(); });
    [Fact] public void Request_requires_accept_reject_is_terminal_and_current_is_not_repeated() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var toc = new XYTableOfContents(new XYTableOfContentsState(Sections, "intro")); var count = 0; toc.SectionRequested += (_, request) => { count++; request.Reject(); request.Accept(); }; toc.SelectSection("data"); toc.SelectSection("intro"); Assert.Equal("intro", toc.CurrentSectionId); Assert.Equal(1, count); });
    [Fact] public void Accepted_selection_commits_shared_state_and_closes_popup() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var state = new XYTableOfContentsState(Sections, "intro"); var toc = new XYTableOfContents(state, XYTableOfContentsVariant.Compact); toc.SectionRequested += (_, request) => request.Accept(); var window = XyuiBatchTestHost.Show(toc); Dispatcher.UIThread.RunJobs(); var trigger = toc.GetVisualDescendants().OfType<XYButton>().Single(); trigger.RaiseEvent(new RoutedEventArgs(Button.ClickEvent)); Assert.True(toc.Popup.IsOpen); toc.SelectSection("data"); Dispatcher.UIThread.RunJobs(); Assert.Equal("data", state.CurrentSectionId); Assert.False(toc.Popup.IsOpen); var refreshedTrigger = toc.GetVisualDescendants().OfType<XYButton>().Single(); Assert.Contains(refreshedTrigger.GetVisualDescendants().OfType<TextBlock>(), x => x.Text == "配置 / 数据集"); window.Close(); });
    [Fact] public void Commit_returns_false_for_current_and_state_is_shared() { var state = new XYTableOfContentsState(Sections, "intro"); var changed = 0; state.Changed += (_, _) => changed++; Assert.False(state.Commit("intro")); Assert.Equal(0, changed); var compact = new XYTableOfContents(state, XYTableOfContentsVariant.Compact); Assert.Same(state, compact.State); }
    [Fact] public void Children_are_grouped_by_parent_id() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var sections = new[] { new XYTocSection("intro", "概览", 1), new XYTocSection("setup", "配置", 1), new XYTocSection("api", "API", 1), new XYTocSection("data", "数据集", 2, "setup"), new XYTocSection("map", "地图基础", 2, "setup") }; var toc = new XYTableOfContents(new XYTableOfContentsState(sections, "data")); var window = XyuiBatchTestHost.Show(toc); Dispatcher.UIThread.RunJobs(); var labels = toc.GetVisualDescendants().OfType<TextBlock>().Select(x => x.Text).Where(x => x is not null and not "本页目录").Select(x => x!).ToArray(); Assert.Equal(["概览", "配置", "数据集", "地图基础", "API"], labels); window.Close(); });
    [Fact] public void Child_group_uses_one_continuous_guide() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var toc = new XYTableOfContents(new XYTableOfContentsState(Sections, "data")); var window = XyuiBatchTestHost.Show(toc); Dispatcher.UIThread.RunJobs(); var guides = toc.GetVisualDescendants().OfType<Border>().Where(x => x.Classes.Contains("xyui-toc-level-guide")).ToArray(); Assert.Single(guides); Assert.True(guides[0].Bounds.Height >= 60); window.Close(); });
    [Fact] public void Toc_items_use_dedicated_template_without_action_edge() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var toc = new XYTableOfContents(new XYTableOfContentsState(Sections, "data")); var window = XyuiBatchTestHost.Show(toc); Dispatcher.UIThread.RunJobs(); Assert.All(toc.GetVisualDescendants().OfType<XYTocItem>(), item => Assert.DoesNotContain(item.GetVisualDescendants().OfType<XyuiActionEdge>(), _ => true)); window.Close(); });
    [Fact] public void Compact_popup_preserves_parent_child_group_and_right_check() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var toc = new XYTableOfContents(new XYTableOfContentsState(Sections, "data"), XYTableOfContentsVariant.Compact); var window = XyuiBatchTestHost.Show(toc); Dispatcher.UIThread.RunJobs(); var trigger = toc.GetVisualDescendants().OfType<XYButton>().Single(); trigger.RaiseEvent(new RoutedEventArgs(Button.ClickEvent)); var panel = Assert.IsType<Border>(toc.Popup.Child); var group = panel.GetVisualDescendants().OfType<Grid>().Single(x => x.Classes.Contains("xyui-toc-child-group")); var child = group.Children.OfType<StackPanel>().Single().Children.OfType<XYTocItem>().Single(x => x.Classes.Contains("xyui-toc-current")); var check = ((Grid)child.Content!).Children.OfType<XYIcon>().Single(x => x.Classes.Contains("xyui-toc-menu-check")); Assert.Equal(2, Grid.GetColumn(check)); Assert.True(check.IsVisible); window.Close(); });
    [Fact] public void Level3_is_not_rendered() { var toc = new XYTableOfContents([new XYTocSection("a", "A", 1), new XYTocSection("deep", "Deep", 3)]); Assert.DoesNotContain(toc.GetVisualDescendants().OfType<TextBlock>(), x => x.Text == "Deep"); }
}
