using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Headless;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Threading;
using Avalonia.VisualTree;
using XYUI.Avalonia.Controls;
using XYUI.Avalonia.Gallery;

namespace XYUI.Avalonia.Tests;

[Collection("XyuiHeadless")]
public sealed class XYUI3ContextToolbarBoardTests : IClassFixture<XyuiHeadlessFixture>
{
    readonly XyuiHeadlessFixture _fx;
    public XYUI3ContextToolbarBoardTests(XyuiHeadlessFixture fx) => _fx = fx;
    [Fact] public void Enter_executes_action() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var board = TestData.Board(); board.AttachTrigger(new XYSplitButton()); var executed = ""; board.ActionExecuted += (_, action) => executed = action.Label; board.RaiseEvent(TestData.Key(Key.Enter)); Assert.Equal("点标记", executed); });
    [Fact] public void Escape_closes_board() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var board = TestData.Board(); board.AttachTrigger(new XYSplitButton()); board.Open(); board.RaiseEvent(TestData.Key(Key.Escape)); Assert.False(board.IsOpen); });
    [Fact] public void Outside_click_closes_board() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var board = TestData.Board(); board.AttachTrigger(new XYSplitButton()); board.Open(); board.DismissOutside(); Assert.False(board.IsOpen); });
    [Fact] public void Repeated_open_close_has_no_visual_residue() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var board = TestData.Board(); var anchor = new XYSplitButton(); board.AttachTrigger(anchor); var child = board.Popup.Child; board.Open(); board.Close(); board.Open(); Assert.Same(child, board.Popup.Child); Assert.Same(anchor, board.Popup.PlacementTarget); });
    [Fact] public void Dropdown_board_uses_real_menu_and_cascade_items() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var board = TestData.Board(); Assert.Equal(3, board.Menu.Items.Count); Assert.Equal(3, board.SubMenus.Count); Assert.All(board.Menu.Items.OfType<XYMenuItem>(), item => Assert.True(item.HasSubMenu)); Assert.All(board.SubMenus, submenu => Assert.NotEmpty(submenu.ChildMenu.Items)); });
    [Fact] public void Dropdown_board_opens_hovered_submenu() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var board = TestData.Board(); board.AttachTrigger(new XYSplitButton()); board.Open(); board.Menu.Items.OfType<XYMenuItem>().ElementAt(1).OpenSubMenu(); Assert.True(board.SubMenus[1].EffectiveVisible); Assert.Equal("道路", board.SubMenus[1].ChildMenu.Items.OfType<XYMenuItem>().First().Label); board.Close(); });
    [Fact] public void Split_button_remains_anchor_after_close_and_reopen() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var split = new XYSplitButton { Content = "道路" }; var board = TestData.Board(); var window = XyuiBatchTestHost.Show(new StackPanel { Children = { split, board } }); board.AttachTrigger(split); board.Open(); board.Close(); board.Toggle(); Assert.Same(split, board.Anchor); window.Close(); });
    [Fact] public void Opening_child_does_not_move_root_menu() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var split = new XYSplitButton { Content = "道路" }; var board = TestData.Board(); var window = XyuiBatchTestHost.Show(new StackPanel { Children = { split, board } }); board.AttachTrigger(split); board.Open(); Dispatcher.UIThread.RunJobs(); var before = board.RootMenuSurface.Bounds; board.SubMenus[1].Open(); Dispatcher.UIThread.RunJobs(); var after = board.RootMenuSurface.Bounds; Assert.Equal(before.X, after.X, 0.5); Assert.Equal(before.Y, after.Y, 0.5); window.Close(); });
    [Fact] public void Child_menu_tracks_trigger_row() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var split = new XYSplitButton { Content = "道路" }; var board = TestData.Board(); var window = XyuiBatchTestHost.Show(new StackPanel { Children = { split, board } }); window.Width = 900; window.Height = 600; board.AttachTrigger(split); board.Open(); board.SubMenus[1].Open(); Dispatcher.UIThread.RunJobs(); var trigger = board.Menu.Items.OfType<XYMenuItem>().ElementAt(1); var point = trigger.TranslatePoint(new Point(0, 0), board.OverlayHost!)!.Value; var child = board.ChildMenuSurfaces[1]; Assert.InRange(Math.Abs(point.Y - child.Bounds.Top), 0, 6); window.Close(); });
    [Fact] public void Overlay_menus_stay_inside_owner_bounds() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var split = new XYSplitButton { Content = "道路" }; var board = TestData.Board(); var window = XyuiBatchTestHost.Show(new StackPanel { Children = { split, board } }); board.AttachTrigger(split); board.Open(); board.SubMenus[2].Open(); Dispatcher.UIThread.RunJobs(); var owner = board.OverlayHost!.Bounds; AssertInside(board.RootMenuSurface.Bounds, owner); Assert.All(board.ChildMenuSurfaces, child => AssertInside(child.Bounds, owner)); window.Close(); });
    [Fact] public void Submenu_width_does_not_expand_root_geometry() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var split = new XYSplitButton { Content = "道路" }; var board = TestData.Board(); var window = XyuiBatchTestHost.Show(new StackPanel { Children = { split, board } }); board.AttachTrigger(split); board.Open(); Dispatcher.UIThread.RunJobs(); var width = board.RootMenuSurface.Bounds.Width; board.SubMenus[1].Open(); Dispatcher.UIThread.RunJobs(); Assert.Equal(width, board.RootMenuSurface.Bounds.Width, 0.5); window.Close(); });
    [Fact] public void Real_pointer_press_outside_closes_board() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var split = new XYSplitButton { Content = "道路" }; var board = TestData.Board(); var window = XyuiBatchTestHost.Show(new StackPanel { Children = { split, board } }); board.AttachTrigger(split); board.Open(); Dispatcher.UIThread.RunJobs(); window.MouseDown(new Point(window.ClientSize.Width - 4, window.ClientSize.Height - 4), MouseButton.Left); Dispatcher.UIThread.RunJobs(); Assert.False(board.IsOpen); window.Close(); });
    [Fact] public void Real_pointer_press_inside_keeps_board_open() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var split = new XYSplitButton { Content = "道路" }; var board = TestData.Board(); var window = XyuiBatchTestHost.Show(new StackPanel { Children = { split, board } }); board.AttachTrigger(split); board.Open(); Dispatcher.UIThread.RunJobs(); var point = board.RootMenuSurface.TranslatePoint(new Point(12, 12), window)!.Value; window.MouseDown(point, MouseButton.Left); Dispatcher.UIThread.RunJobs(); Assert.True(board.IsOpen); window.Close(); });
    [Fact] public void Real_pointer_press_inside_child_keeps_board_open() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var split = new XYSplitButton { Content = "道路" }; var board = TestData.Board(); var window = XyuiBatchTestHost.Show(new StackPanel { Children = { split, board } }); board.AttachTrigger(split); board.Open(); board.SubMenus[1].Open(); Dispatcher.UIThread.RunJobs(); var point = board.ChildMenuSurfaces[1].TranslatePoint(new Point(12, 12), window)!.Value; window.MouseDown(point, MouseButton.Left); Dispatcher.UIThread.RunJobs(); Assert.True(board.IsOpen); window.Close(); });
    [Fact] public void Resize_reflows_visible_child_inside_owner() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var split = new XYSplitButton { Content = "道路" }; var board = TestData.Board(); var window = XyuiBatchTestHost.Show(new StackPanel { Children = { split, board } }); board.AttachTrigger(split); board.Open(); board.SubMenus[2].Open(); Dispatcher.UIThread.RunJobs(); window.Width = 220; window.Height = 180; Dispatcher.UIThread.RunJobs(); Dispatcher.UIThread.RunJobs(); var owner = board.OverlayHost!.Bounds; AssertInside(board.RootMenuSurface.Bounds, owner); AssertInside(board.ChildMenuSurfaces[2].Bounds, owner); window.Close(); });
    [Fact] public void Context_menu_uses_compact_density() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var split = new XYSplitButton { Content = "道路" }; var board = TestData.Board(); var window = XyuiBatchTestHost.Show(new StackPanel { Children = { split, board } }); board.AttachTrigger(split); board.Open(); Dispatcher.UIThread.RunJobs(); Assert.Equal(128, board.RootMenuSurface.Bounds.Width, 0.5); Assert.Equal(32, board.Menu.Items.OfType<XYMenuItem>().First().Bounds.Height, 0.5); Assert.All(board.Menu.Items.OfType<XYMenuItem>(), item => Assert.Equal(new Thickness(8, 4), item.Padding)); Assert.Equal(new CornerRadius(6), board.RootMenuSurface.CornerRadius); Assert.InRange(board.HintBar.Height, 22, 24); Assert.Contains(board.RootMenuSurface.GetVisualDescendants().OfType<TextBlock>(), x => x.Classes.Contains("xyui-context-board-header") && x.Padding == new Thickness(8, 4)); window.Close(); });
    [Fact] public void Selecting_marker_updates_split_button_content() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var window = XyuiBatchTestHost.Show(preview); Dispatcher.UIThread.RunJobs(); var board = preview.GetVisualDescendants().OfType<XYContextDropdownBoard>().ElementAt(1); var split = preview.GetVisualDescendants().OfType<XYSplitButton>().ElementAt(1); board.SubMenus[0].ChildMenu.Items.OfType<XYMenuItem>().First().Activate(); Assert.Equal("点标记", split.Content); window.Close(); });
    [Fact] public void Selecting_region_updates_split_button_content() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var window = XyuiBatchTestHost.Show(preview); Dispatcher.UIThread.RunJobs(); var board = preview.GetVisualDescendants().OfType<XYContextDropdownBoard>().ElementAt(1); var split = preview.GetVisualDescendants().OfType<XYSplitButton>().ElementAt(1); board.SubMenus[2].ChildMenu.Items.OfType<XYMenuItem>().First().Activate(); Assert.Equal("区域", split.Content); window.Close(); });
    [Fact] public void Selected_tool_survives_dropdown_close() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var window = XyuiBatchTestHost.Show(preview); Dispatcher.UIThread.RunJobs(); var board = preview.GetVisualDescendants().OfType<XYContextDropdownBoard>().ElementAt(1); var split = preview.GetVisualDescendants().OfType<XYSplitButton>().ElementAt(1); board.SubMenus[2].ChildMenu.Items.OfType<XYMenuItem>().First().Activate(); board.Close(); Assert.Equal("区域", split.Content); window.Close(); });
    [Fact] public void Gallery_split_buttons_do_not_use_unicode_chevron() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); Assert.DoesNotContain(preview.GetVisualDescendants().OfType<XYSplitButton>(), split => split.Content?.ToString()?.Contains("▼") == true); });
    [Fact] public void Split_button_width_is_fixed_across_selected_actions() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var window = XyuiBatchTestHost.Show(preview); Dispatcher.UIThread.RunJobs(); var board = preview.GetVisualDescendants().OfType<XYContextDropdownBoard>().ElementAt(1); var split = preview.GetVisualDescendants().OfType<XYSplitButton>().ElementAt(1); Assert.Equal(96, split.Width, 0.5); var width = split.Bounds.Width; board.SubMenus[1].ChildMenu.Items.OfType<XYMenuItem>().Last().Activate(); Dispatcher.UIThread.RunJobs(); Assert.Equal(width, split.Bounds.Width, 0.5); Assert.Equal(96, split.Bounds.Width, 0.5); window.Close(); });
    [Fact] public void Dropdown_popup_host_does_not_change_gallery_flow() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var window = XyuiBatchTestHost.Show(preview); Dispatcher.UIThread.RunJobs(); var bars = preview.GetVisualDescendants().OfType<XYContextToolbar>().ToArray(); var before = bars[2].Bounds.Top; var board = preview.GetVisualDescendants().OfType<XYContextDropdownBoard>().ElementAt(1); Assert.True(board.IsOpen); Assert.True(board.Bounds.Height <= 2); board.Close(); Dispatcher.UIThread.RunJobs(); board.Open(bars[1].GetVisualDescendants().OfType<XYSplitButton>().Single()); Dispatcher.UIThread.RunJobs(); Assert.Equal(before, bars[2].Bounds.Top); Assert.True(board.Bounds.Height <= 2); window.Close(); });
    [Fact] public void Gallery_context_toolbar_section_uses_real_components() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var document = XYUI3DocumentationCatalog.ContextToolbarDocument(); Assert.Equal(3, preview.GetVisualDescendants().OfType<XYContextToolbar>().Count()); Assert.True(document.HasLiveExamples); Assert.Contains(preview.GetVisualDescendants().OfType<XYContextDropdownBoard>(), board => board.Popup.IsLightDismissEnabled); });
    [Fact] public void Gallery_live_and_composition_do_not_duplicate_demos() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var document = XYUI3DocumentationCatalog.ContextToolbarDocument(); var live = document.LiveExamplesFactory!(); var composition = document.CompositionFactory!(); Assert.Equal(3, live.GetVisualDescendants().OfType<XYContextToolbar>().Count()); Assert.Single(composition.GetVisualDescendants().OfType<XYContextToolbar>()); });
    [Fact] public void Gallery_open_demo_shows_board_after_layout() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var window = XyuiBatchTestHost.Show(preview); Dispatcher.UIThread.RunJobs(); var boards = preview.GetVisualDescendants().OfType<XYContextDropdownBoard>().ToArray(); Assert.True(boards[1].IsOpen); Assert.True(boards[1].RootMenuSurface.IsVisible, $"bounds={boards[1].RootMenuSurface.Bounds} host={boards[1].OverlayHost?.Bounds}"); Assert.True(boards[1].RootMenuSurface.Bounds.Width > 0, $"bounds={boards[1].RootMenuSurface.Bounds} host={boards[1].OverlayHost?.Bounds}"); window.Close(); });
    [Fact] public void Gallery_root_menu_tracks_real_split_button_anchor() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var window = XyuiBatchTestHost.Show(preview); window.Width = 1200; window.Height = 900; Dispatcher.UIThread.RunJobs(); var bar = preview.GetVisualDescendants().OfType<XYContextToolbar>().ElementAt(1); var anchor = bar.GetVisualDescendants().OfType<XYSplitButton>().Single(); var board = preview.GetVisualDescendants().OfType<XYContextDropdownBoard>().ElementAt(1); board.Open(anchor); Dispatcher.UIThread.RunJobs(); var expected = anchor.TranslatePoint(new Point(0, anchor.Bounds.Height), board.OverlayHost!)!.Value; var actual = board.RootMenuSurface.TranslatePoint(new Point(0, 0), board.OverlayHost!)!.Value; Assert.True(Math.Abs(actual.X - expected.X) <= 6, $"x actual={actual} expected={expected} owner={board.OverlayHost!.Bounds}"); Assert.True(Math.Abs(actual.Y - expected.Y) <= 6, $"y actual={actual} expected={expected} owner={board.OverlayHost!.Bounds}"); window.Close(); });
    [Fact] public void Gallery_root_menu_reflows_when_scroll_moves_anchor() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var scroll = new ScrollViewer { Width = 900, Height = 500, Content = preview }; var window = XyuiBatchTestHost.Show(scroll); window.Width = 900; window.Height = 500; Dispatcher.UIThread.RunJobs(); var bar = preview.GetVisualDescendants().OfType<XYContextToolbar>().ElementAt(1); var anchor = bar.GetVisualDescendants().OfType<XYSplitButton>().Single(); var board = preview.GetVisualDescendants().OfType<XYContextDropdownBoard>().ElementAt(1); board.Close(); board.Open(anchor); Dispatcher.UIThread.RunJobs(); scroll.Offset = new global::Avalonia.Vector(0, 80); Dispatcher.UIThread.RunJobs(); var expected = anchor.TranslatePoint(new Point(0, anchor.Bounds.Height), board.OverlayHost!)!.Value; var actual = board.RootMenuSurface.TranslatePoint(new Point(0, 0), board.OverlayHost!)!.Value; Assert.True(Math.Abs(actual.Y - expected.Y) <= 6, $"actual={actual} expected={expected} host={board.OverlayHost!.Bounds}"); window.Close(); });
    [Fact] public void Gallery_offscreen_open_board_does_not_float_at_window_edge() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var content = new StackPanel { Children = { new Border { Height = 1000 }, preview } }; var scroll = new ScrollViewer { Width = 900, Height = 500, Content = content }; var window = XyuiBatchTestHost.Show(scroll); window.Width = 900; window.Height = 500; Dispatcher.UIThread.RunJobs(); var board = preview.GetVisualDescendants().OfType<XYContextDropdownBoard>().ElementAt(1); Assert.False(board.RootMenuSurface.IsVisible, $"owner={board.OverlayHost!.Bounds}"); scroll.Offset = new global::Avalonia.Vector(0, 900); Dispatcher.UIThread.RunJobs(); Assert.True(board.RootMenuSurface.IsVisible); window.Close(); });
    [Fact] public void Gallery_overlay_host_fills_dock_root() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var preview = XYUI3GalleryCatalog.CreatePreview(XYUI3GalleryCatalog.ContextToolbarId); var window = XyuiBatchTestHost.Show(new DockPanel { Children = { new Border { Height = 32 }, preview } }); window.Width = 900; window.Height = 500; Dispatcher.UIThread.RunJobs(); var board = preview.GetVisualDescendants().OfType<XYContextDropdownBoard>().ElementAt(1); Assert.True(board.OverlayHost!.Bounds.Width > 0, $"host={board.OverlayHost.Bounds}"); Assert.True(board.OverlayHost.Bounds.Height > 0, $"host={board.OverlayHost.Bounds}"); window.Close(); });
    [Fact] public void Toolbar_groups_fit_inside_toolbar_bounds() => _fx.Run(() => { XyuiBatchTestHost.Prepare(); var toolbar = new XYContextToolbar(new XYContextGroup("编辑", new XYButton { Content = "选择", Height = 32 })); var window = XyuiBatchTestHost.Show(toolbar); Dispatcher.UIThread.RunJobs(); var group = toolbar.GetVisualDescendants().OfType<XYContextGroup>().Single(); var button = group.GetVisualDescendants().OfType<XYButton>().Single(); Assert.True(group.Bounds.Bottom <= toolbar.Bounds.Height + 0.1); Assert.True(button.Bounds.Bottom <= group.Bounds.Height + 0.1); window.Close(); });
    static void AssertInside(Rect inner, Rect owner) { Assert.True(inner.Left >= owner.Left - 0.5, $"left inner={inner} owner={owner}"); Assert.True(inner.Top >= owner.Top - 0.5, $"top inner={inner} owner={owner}"); Assert.True(inner.Right <= owner.Right + 0.5, $"right inner={inner} owner={owner}"); Assert.True(inner.Bottom <= owner.Bottom + 0.5, $"bottom inner={inner} owner={owner}"); }
}

static class TestData
{
    internal static XYContextDropdownBoard Board() => new("绘制", [new("point", "点"), new("line", "线"), new("area", "面")], new Dictionary<string, IReadOnlyList<XYContextAction>> { ["point"] = [new("marker", "点标记"), new("poi", "兴趣点")], ["line"] = [new("road", "道路"), new("boundary", "边界线"), new("river", "河流")], ["area"] = [new("region", "区域"), new("blocked", "禁行区"), new("parcel", "地块")] });
    internal static KeyEventArgs Key(Key key) => new() { RoutedEvent = InputElement.KeyDownEvent, Key = key };
    internal sealed class Command(Action<object?> execute) : System.Windows.Input.ICommand { public event EventHandler? CanExecuteChanged { add { } remove { } } public bool CanExecute(object? p) => true; public void Execute(object? p) => execute(p); }
}
