[CmdletBinding()]
param([Parameter(Position=0)][ValidateSet('register','begin','list','inspect','amend','release','close','reap')][string]$Command='list',[string]$TaskId,[string]$Role,[string]$Owner,[string]$Workspace,[string[]]$WriteScope,[string[]]$ExpectedDependencies,[string[]]$AddWriteScope,[string]$Coordinator,[string]$Reason,[string]$CloseReason,[string]$RepositoryRoot)
$ErrorActionPreference='Stop';. (Join-Path $PSScriptRoot 'task-flight-plan.common.ps1')
function Find($r,[string]$id){@($r.tasks|?{$_.TaskId -eq $id})|select -First 1}
function Save([string]$Root,$Reg,$Task,[string]$Event,[string]$Why='', [string]$Coordinator=''){SaveReg -R $Root -Reg $Reg;Audit -R $Root -Event $Event -Task $Task -Reason $Why -Coordinator $Coordinator}
try{
 $root=Repo $RepositoryRoot;$r=ReadReg $root
 switch($Command){
  'register'{if(!$TaskId -or !$Owner -or !$Workspace -or !$WriteScope){Fail INVALID_INPUT 'TaskId Owner Workspace WriteScope required'};if(Find $r $TaskId){Fail TASK_EXISTS $TaskId};$t=[ordered]@{TaskId=$TaskId;Role=$Role;Owner=$Owner;Workspace=(NormWorkspace $Workspace);WriteScope=(Scopes $WriteScope $Workspace);ExpectedDependencies=@($ExpectedDependencies);Status='REGISTERED';BaselineHead=(Head $root);RegisteredAt=(Now);ActivatedAt=$null;ReleasedAt=$null;ClosedAt=$null;CloseReason=$null};$r.tasks=@($r.tasks)+[pscustomobject]$t;Save $root $r $t 'REGISTERED';Write-Host "REGISTERED $TaskId"}
  'begin'{if(!$TaskId){Fail INVALID_INPUT 'TaskId required'};$t=Find $r $TaskId;if(!$t){Fail NOT_FOUND $TaskId};if($t.Status -ne 'REGISTERED'){Fail INVALID_TRANSITION "$($t.Status) -> ACTIVE"};$tw=[string]$t.Workspace;$c=Conflict -Reg $r -Wanted @($t.WriteScope) -TaskId $TaskId -WantedWorkspace $tw;if($c){Fail OWNERSHIP_CONFLICT "$TaskId overlaps $($c.TaskId)"};$t.Status='ACTIVE';$t.ActivatedAt=Now;Save $root $r $t 'ACTIVE';Write-Host "ACTIVE $TaskId"}
  'list'{Write-Host "ACTIVE TASKS: $(@($r.tasks|?{$_.Status -eq 'ACTIVE'}).Count)";@($r.tasks|?{$_.Status -eq 'ACTIVE'})|%{Write-Host "$($_.TaskId) $($_.Owner) $($_.Status)"}}
  'inspect'{if(!$TaskId){Fail INVALID_INPUT 'TaskId required'};$t=Find $r $TaskId;if(!$t){$h=Get-Content (HistPath $root) -ErrorAction SilentlyContinue|?{$_ -match ('"TaskId":"'+[regex]::Escape($TaskId)+'"')};if(!$h){Fail NOT_FOUND $TaskId};Write-Host ($h -join "`n")}else{$t|ConvertTo-Json -Depth 10}}
  'amend'{if(!$TaskId -or !$AddWriteScope){Fail INVALID_INPUT 'TaskId AddWriteScope required'};$t=Find $r $TaskId;if(!$t){Fail NOT_FOUND $TaskId};$add=Scopes $AddWriteScope ([string]$t.Workspace);$c=Conflict -Reg $r -Wanted $add -TaskId $TaskId -WantedWorkspace ([string]$t.Workspace);if($c){Write-Host "AMEND BLOCKED / OWNERSHIP_CONFLICT $($c.TaskId)";exit 1};$t.WriteScope=@((@($t.WriteScope)+@($add))|sort -Unique);Save $root $r $t 'AMEND APPROVED';Write-Host 'AMEND APPROVED'}
  'release'{if(!$TaskId){Fail INVALID_INPUT 'TaskId required'};$t=Find $r $TaskId;if(!$t){Fail NOT_FOUND $TaskId};if($t.Status -eq 'RELEASED'){Write-Host "already RELEASED $TaskId";break};if($t.Status -ne 'ACTIVE'){Fail INVALID_TRANSITION "$($t.Status) -> RELEASED"};$t.Status='RELEASED';$t.ReleasedAt=Now;Save $root $r $t 'RELEASED';Write-Host "RELEASED $TaskId"}
  'close'{if(!$TaskId){Fail INVALID_INPUT 'TaskId required'};$t=Find $r $TaskId;if(!$t){Fail NOT_FOUND $TaskId};if($t.Status -ne 'RELEASED'){Fail INVALID_TRANSITION "$($t.Status) -> CLOSED"};$t.Status='CLOSED';$t.ClosedAt=Now;$t.CloseReason=$CloseReason;$r.tasks=@($r.tasks|?{$_.TaskId -ne $TaskId});Save $root $r $t 'CLOSED' $CloseReason;Write-Host "CLOSED $TaskId"}
  'reap'{if(!$TaskId -or !$Coordinator -or !$Reason){Fail INVALID_INPUT 'TaskId Coordinator Reason required'};$t=Find $r $TaskId;if(!$t){Fail NOT_FOUND $TaskId};if($t.Status -ne 'ACTIVE'){Fail INVALID_TRANSITION "$($t.Status) -> CLOSED"};$t.Status='CLOSED';$t.ClosedAt=Now;$t.CloseReason="ABANDONED/$Reason";$r.tasks=@($r.tasks|?{$_.TaskId -ne $TaskId});Save $root $r $t 'REAP' $t.CloseReason $Coordinator;Write-Host $t.CloseReason}
 }
}catch{Write-Host $_.Exception.Message;exit 1}
