using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Styling;

namespace XYUI.Avalonia.Controls;

public static partial class XyuiComponentStyles
{
    static void SidebarRailTabs(Styles styles)
    {
        var sidebar = new Style(x => x.OfType<XYSidebar>().Class("xyui-sidebar")); Brush(sidebar, Border.BackgroundProperty, "XY.Brush.Surface.Panel"); sidebar.Setters.Add(new Setter(Border.WidthProperty, XyuiComponentTokens.SidebarWidth)); sidebar.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(8))); styles.Add(sidebar);
        var collapsed = new Style(x => x.OfType<XYSidebar>().Class("xyui-sidebar-collapsed")); collapsed.Setters.Add(new Setter(Border.WidthProperty, XyuiComponentTokens.NavigationRailWidth)); collapsed.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(0))); styles.Add(collapsed);
        var header = new Style(x => x.OfType<Border>().Class("xyui-sidebar-header")); Brush(header, Border.BackgroundProperty, "XY.Brush.Surface.PanelAlt"); header.Setters.Add(new Setter(Border.HeightProperty, XyuiComponentTokens.SidebarHeaderHeight)); header.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(14, 0))); styles.Add(header);
        var collapse = new Style(x => x.OfType<XYIconButton>().Class("xyui-sidebar-collapse")); collapse.Setters.Add(new Setter(Control.WidthProperty, 24d)); collapse.Setters.Add(new Setter(Control.HeightProperty, 30d)); collapse.Setters.Add(new Setter(Control.HorizontalAlignmentProperty, HorizontalAlignment.Right)); collapse.Setters.Add(new Setter(Control.VerticalAlignmentProperty, VerticalAlignment.Center)); collapse.Setters.Add(new Setter(Button.BackgroundProperty, Brushes.Transparent)); collapse.Setters.Add(new Setter(Button.BorderThicknessProperty, new Thickness(0))); styles.Add(collapse);
        TextStyle(styles, "xyui-sidebar-title", 13, 600, "XY.Brush.Text.Primary");
        var rail = new Style(x => x.OfType<XYNavigationRail>().Class("xyui-navigation-rail")); Brush(rail, Border.BackgroundProperty, "XY.Brush.Surface.Panel"); rail.Setters.Add(new Setter(Border.WidthProperty, XyuiComponentTokens.NavigationRailWidth)); rail.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(7))); styles.Add(rail);
        var railItem = new Style(x => x.OfType<XYNavigationItem>().Class("xyui-rail-item")); railItem.Setters.Add(new Setter(Border.WidthProperty, 40d)); railItem.Setters.Add(new Setter(Border.HeightProperty, XyuiComponentTokens.NavigationRailItemHeight)); railItem.Setters.Add(new Setter(Border.HorizontalAlignmentProperty, HorizontalAlignment.Center)); railItem.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(0))); styles.Add(railItem);
        var railLabel = new Style(x => x.OfType<XYNavigationItem>().Class("xyui-rail-item").Descendant().OfType<TextBlock>().Class("xyui-navigation-label")); railLabel.Setters.Add(new Setter(Visual.IsVisibleProperty, false)); styles.Add(railLabel);
        var railIcon = new Style(x => x.OfType<XYNavigationItem>().Class("xyui-rail-item").Descendant().OfType<XYIcon>().Class("xyui-navigation-icon")); railIcon.Setters.Add(new Setter(Control.WidthProperty, 16d)); railIcon.Setters.Add(new Setter(Control.HeightProperty, 16d)); railIcon.Setters.Add(new Setter(Control.MarginProperty, new Thickness(0))); railIcon.Setters.Add(new Setter(Control.HorizontalAlignmentProperty, HorizontalAlignment.Center)); styles.Add(railIcon);
        var railExpand = new Style(x => x.OfType<XYIconButton>().Class("xyui-rail-expand")); railExpand.Setters.Add(new Setter(Control.WidthProperty, 40d)); railExpand.Setters.Add(new Setter(Control.HeightProperty, 40d)); railExpand.Setters.Add(new Setter(Control.HorizontalAlignmentProperty, HorizontalAlignment.Center)); railExpand.Setters.Add(new Setter(Button.BackgroundProperty, Brushes.Transparent)); railExpand.Setters.Add(new Setter(Button.BorderThicknessProperty, new Thickness(0))); styles.Add(railExpand);
        var context = new Style(x => x.OfType<TextBlock>().Class("xyui-sidebar-context-label")); context.Setters.Add(new Setter(Control.HeightProperty, 20d)); context.Setters.Add(new Setter(Control.MarginProperty, new Thickness(6, 8, 6, 4))); Set(context, TextBlock.ForegroundProperty, "XY.Brush.Text.Secondary"); styles.Add(context);
        var contextItem = new Style(x => x.OfType<TextBlock>().Class("xyui-sidebar-context-item")); contextItem.Setters.Add(new Setter(Control.HeightProperty, 28d)); Set(contextItem, TextBlock.ForegroundProperty, "XY.Brush.Text.Primary"); styles.Add(contextItem);
        var contextIcon = new Style(x => x.OfType<XYIcon>().Class("xyui-sidebar-context-icon")); contextIcon.Setters.Add(new Setter(Control.WidthProperty, 14d)); contextIcon.Setters.Add(new Setter(Control.HeightProperty, 14d)); contextIcon.Setters.Add(new Setter(Control.MarginProperty, new Thickness(16, 0, 0, 0))); Set(contextIcon, XYIcon.StrokeProperty, "XY.Brush.Text.Secondary"); styles.Add(contextIcon);
        var contextButton = new Style(x => x.OfType<Button>().Class("xyui-sidebar-context-button")); contextButton.Setters.Add(new Setter(Control.HeightProperty, 28d)); contextButton.Setters.Add(new Setter(Button.PaddingProperty, new Thickness(0))); contextButton.Setters.Add(new Setter(Button.BackgroundProperty, Brushes.Transparent)); contextButton.Setters.Add(new Setter(Button.BorderThicknessProperty, new Thickness(0))); styles.Add(contextButton);
        var footer = new Style(x => x.OfType<XYSidebarFooter>().Class("xyui-sidebar-footer")); footer.Setters.Add(new Setter(Border.HeightProperty, 36d)); footer.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(38, 0))); footer.Setters.Add(new Setter(Button.BackgroundProperty, Brushes.Transparent)); footer.Setters.Add(new Setter(Button.BorderThicknessProperty, new Thickness(0))); styles.Add(footer); TextStyle(styles, "xyui-sidebar-footer-label", 13, 400, "XY.Brush.Text.Primary");
        var tabs = new Style(x => x.OfType<XYTabs>().Class("xyui-tabs")); Brush(tabs, Border.BackgroundProperty, "XY.Brush.Surface.Panel"); tabs.Setters.Add(new Setter(Border.HeightProperty, XyuiComponentTokens.TabHeight)); styles.Add(tabs);
        var tab = new Style(x => x.OfType<XYTab>().Class("xyui-tab")); tab.Setters.Add(new Setter(Border.HeightProperty, XyuiComponentTokens.TabHeight)); tab.Setters.Add(new Setter(Border.PaddingProperty, new Thickness(XyuiComponentTokens.TabPaddingX, 0))); tab.Setters.Add(new Setter(Border.BackgroundProperty, Brushes.Transparent)); styles.Add(tab);
        var tabClose = new Style(x => x.OfType<XYIconButton>().Class("xyui-tab-close")); tabClose.Setters.Add(new Setter(Control.WidthProperty, 28d)); tabClose.Setters.Add(new Setter(Control.HeightProperty, 28d)); tabClose.Setters.Add(new Setter(Control.HorizontalAlignmentProperty, HorizontalAlignment.Center)); tabClose.Setters.Add(new Setter(Control.VerticalAlignmentProperty, VerticalAlignment.Center)); tabClose.Setters.Add(new Setter(Button.PaddingProperty, new Thickness(0))); tabClose.Setters.Add(new Setter(Button.BackgroundProperty, Brushes.Transparent)); tabClose.Setters.Add(new Setter(Button.BorderThicknessProperty, new Thickness(0))); styles.Add(tabClose);
        var selected = new Style(x => x.OfType<XYTab>().Class("xyui-tab-selected")); Brush(selected, Border.BackgroundProperty, "XY.Brush.Surface.Selected"); styles.Add(selected);
        var hover = new Style(x => x.OfType<XYTab>().Class("xyui-tab").Class(":pointerover")); Brush(hover, Border.BackgroundProperty, "XY.Brush.State.Color.Hover"); styles.Add(hover);
        var pressed = new Style(x => x.OfType<XYTab>().Class("xyui-tab").Class(":pressed")); Brush(pressed, Border.BackgroundProperty, "XY.Brush.State.Color.Pressed"); styles.Add(pressed);
        var focus = new Style(x => x.OfType<XYTab>().Class("xyui-tab").Class(":focus")); focus.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(1))); Brush(focus, Border.BorderBrushProperty, "XY.Brush.Border.Color.Selected"); styles.Add(focus);
        var disabled = new Style(x => x.OfType<XYTab>().Class("xyui-tab").Class(":disabled")); Set(disabled, Border.BackgroundProperty, "XY.Brush.State.Disabled.Background"); styles.Add(disabled);
        var activeText = new Style(x => x.OfType<XYTab>().Class("xyui-tab-selected").Descendant().OfType<TextBlock>().Class("xyui-tab-label")); Set(activeText, TextBlock.ForegroundProperty, "XY.Brush.Accent.Strong"); activeText.Setters.Add(new Setter(TextBlock.FontWeightProperty, FontWeight.Medium)); styles.Add(activeText);
        var tabAccent = new Style(x => x.OfType<Border>().Class("xyui-tab-accent")); Brush(tabAccent, Border.BackgroundProperty, "XY.Brush.Accent.Default"); tabAccent.Setters.Add(new Setter(Border.HeightProperty, 3d)); tabAccent.Setters.Add(new Setter(Border.VerticalAlignmentProperty, global::Avalonia.Layout.VerticalAlignment.Bottom)); styles.Add(tabAccent);
        var tabDivider = new Style(x => x.OfType<Border>().Class("xyui-tab-divider")); Brush(tabDivider, Border.BackgroundProperty, "XY.Brush.Border.Color.Subtle"); styles.Add(tabDivider);
        TextStyle(styles, "xyui-tab-label", 13, 400, "XY.Brush.Text.Secondary");
        var dot = new Style(x => x.OfType<Border>().Class("xyui-tab-modified")); Brush(dot, Border.BackgroundProperty, "XY.Brush.Text.Secondary"); dot.Setters.Add(new Setter(Border.WidthProperty, 3d)); dot.Setters.Add(new Setter(Border.HeightProperty, 3d)); dot.Setters.Add(new Setter(Border.CornerRadiusProperty, new CornerRadius(2))); styles.Add(dot);
    }
}
