// <auto-generated>
// 由 tools/shaders/embed_basic_3d_shaders.ps1 在 spirv-val 通过后生成。
// 不要手工编辑。当心爱的 Editor 被你砸掉。
// </auto-generated>
namespace FluidWarfare.Render.Vulkan.Shaders;

/// <summary>
/// 预编译 SPIR-V 着色器字节码。
///
/// 由标准工具链生成：
///   GLSL → glslangValidator → .spv → spirv-val → embed_basic_3d_shaders.ps1 → 本文件
///
/// 当前 8.R.3 阶段，如果 .spv 尚未通过 spirv-val，此文件保持空数组占位。
/// HasValidatedBasic3dShaders 为 false，VulkanScene3dRunGate 不会返回 Ready。
/// </summary>
internal static class CompiledShaders
{
    /// <summary>
    /// 基础 3D 顶点着色器 SPIR-V。
    /// 由 embed_basic_3d_shaders.ps1 填入字节。
    /// 空数组表示未通过 spirv-val 验证。
    /// </summary>
    public static uint[] Basic3dVert { get; internal set; } = [];

    /// <summary>
    /// 基础 3D 片段着色器 SPIR-V。
    /// 由 embed_basic_3d_shaders.ps1 填入字节。
    /// 空数组表示未通过 spirv-val 验证。
    /// </summary>
    public static uint[] Basic3dFrag { get; internal set; } = [];

    /// <summary>
    /// 顶点着色器是否通过 spirv-val 验证。
    /// </summary>
    public static bool Basic3dVertexValidatedBySpirvVal { get; internal set; }

    /// <summary>
    /// 片段着色器是否通过 spirv-val 验证。
    /// </summary>
    public static bool Basic3dFragmentValidatedBySpirvVal { get; internal set; }

    /// <summary>
    /// 两个 basic_3d shader 是否都存在且通过 spirv-val 验证。
    /// VulkanScene3dRunGate.Evaluate() 使用此属性判断是否允许手动触发 Scene3D。
    /// </summary>
    public static bool HasValidatedBasic3dShaders =>
        Basic3dVert.Length > 0 &&
        Basic3dFrag.Length > 0 &&
        Basic3dVertexValidatedBySpirvVal &&
        Basic3dFragmentValidatedBySpirvVal;

    /// <summary>
    /// 重置所有 shader 为空数组和未验证状态。
    /// 用于测试或工具链重建。
    /// </summary>
    internal static void Reset()
    {
        Basic3dVert = [];
        Basic3dFrag = [];
        Basic3dVertexValidatedBySpirvVal = false;
        Basic3dFragmentValidatedBySpirvVal = false;
    }
}
