using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Markup.Xaml.MarkupExtensions;
using Avalonia.Media;
using Avalonia.Styling;

namespace XYUI.Avalonia.Controls;

public static partial class XyuiControlStyles
{
    static void DatePicker(Styles styles) { var root = Input(styles, typeof(XYDatePicker), "xyui-date-picker", 32, false); root.Setters.Add(new Setter(TemplatedControl.TemplateProperty, XYDatePicker.CreateTemplate())); Typography(root); InputStates(styles, typeof(XYDatePicker), "xyui-date-picker"); foreach (var name in new[] { "PART_Year", "PART_Month", "PART_Day", "PART_Previous", "PART_Next", "PART_CalendarButton" }) DatePart(styles, typeof(XYDatePicker), "xyui-date-picker", name); ActivePart(styles, typeof(XYDatePicker), "xyui-date-picker", "Year"); ActivePart(styles, typeof(XYDatePicker), "xyui-date-picker", "Month"); ActivePart(styles, typeof(XYDatePicker), "xyui-date-picker", "Day"); PopupPart(styles, typeof(XYDatePicker), "xyui-date-picker"); DatePopup(styles); FocusEdge(styles, typeof(XYDatePicker), "xyui-date-picker"); }
    static void TimePicker(Styles styles) { var root = Input(styles, typeof(XYTimePicker), "xyui-time-picker", 32, false); root.Setters.Add(new Setter(TemplatedControl.TemplateProperty, XYTimePicker.CreateTemplate())); Typography(root); InputStates(styles, typeof(XYTimePicker), "xyui-time-picker"); foreach (var name in new[] { "PART_Hour", "PART_Minute", "PART_Second", "PART_ClockGlyph", "PART_ScrubIndicator" }) DatePart(styles, typeof(XYTimePicker), "xyui-time-picker", name); ActivePart(styles, typeof(XYTimePicker), "xyui-time-picker", "Hour"); ActivePart(styles, typeof(XYTimePicker), "xyui-time-picker", "Minute"); ActivePart(styles, typeof(XYTimePicker), "xyui-time-picker", "Second"); var indicator = new Style(x => x.OfType<XYTimePicker>().Class("xyui-time-scrubbing").Template().Name("PART_ScrubIndicator")); indicator.Setters.Add(new Setter(Control.IsVisibleProperty, true)); Set(indicator, XYIcon.StrokeProperty, "XY.Brush.Accent.Default"); styles.Add(indicator); TimePopup(styles); FocusEdge(styles, typeof(XYTimePicker), "xyui-time-picker"); }
    static void TimePopup(Styles styles) { var surface = new Style(x => x.OfType<XYTimePicker>().Class("xyui-time-picker").Template().Name("PART_TimePopupSurface")); Set(surface, Border.BackgroundProperty, "XY.Brush.Surface.PanelAlt"); Set(surface, Border.BorderBrushProperty, "XY.Brush.Border.Color.Default"); surface.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(1))); surface.Setters.Add(new Setter(Border.CornerRadiusProperty, new CornerRadius(3))); styles.Add(surface); }
    static void DatePopup(Styles styles) { var surface = new Style(x => x.OfType<XYDatePicker>().Class("xyui-date-picker").Template().Name("PART_DatePopupSurface")); Set(surface, Border.BackgroundProperty, "XY.Brush.Surface.PanelAlt"); Set(surface, Border.BorderBrushProperty, "XY.Brush.Border.Color.Default"); surface.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(1))); surface.Setters.Add(new Setter(Border.CornerRadiusProperty, new CornerRadius(3))); styles.Add(surface); }
    static void Typography(Style style) { Set(style, TemplatedControl.FontFamilyProperty, "XY.Font.UI"); Set(style, TemplatedControl.FontSizeProperty, "XY.FontSize.Body"); Set(style, TemplatedControl.FontWeightProperty, "XY.FontWeight.Normal"); }
    static void InputStates(Styles styles, Type type, string cls) { State(styles, type, cls, ":focus", TemplatedControl.BackgroundProperty, "XY.Brush.Surface.Raised"); State(styles, type, cls, ":disabled", TemplatedControl.BackgroundProperty, "XY.Brush.State.Disabled.Background"); State(styles, type, cls, ":disabled", TemplatedControl.ForegroundProperty, "XY.Brush.State.Disabled.Text"); State(styles, type, cls, ":disabled", TemplatedControl.BorderBrushProperty, "XY.Brush.State.Disabled.Border"); }
    static void DatePart(Styles styles, Type type, string cls, string name) { var part = new Style(x => x.OfType(type).Class(cls).Template().Name(name)); part.Setters.Add(new Setter(Button.TemplateProperty, ActionCellTemplate())); part.Setters.Add(new Setter(Button.BackgroundProperty, Brushes.Transparent)); Set(part, Button.ForegroundProperty, "XY.Brush.Text.Primary"); Set(part, XYIcon.StrokeProperty, "XY.Brush.Text.Secondary"); styles.Add(part); }
    static void ActivePart(Styles styles, Type type, string cls, string segment) { var active = new Style(x => x.OfType(type).Class(cls).Class($"xyui-{(type == typeof(XYDatePicker) ? "date" : "time")}-{segment.ToLowerInvariant()}-active").Template().Name($"PART_{segment}")); Set(active, Button.BackgroundProperty, "XY.Brush.Surface.Selected"); Set(active, Button.ForegroundProperty, "XY.Brush.Accent.Strong"); styles.Add(active); }
    static void PopupPart(Styles styles, Type type, string cls) { var surface = new Style(x => x.OfType(type).Class(cls).Template().Name("PART_CalendarSurface")); Set(surface, Border.BackgroundProperty, "XY.Brush.Surface.PanelAlt"); Set(surface, Border.BorderBrushProperty, "XY.Brush.Border.Color.Default"); surface.Setters.Add(new Setter(Border.BorderThicknessProperty, new Thickness(1))); surface.Setters.Add(new Setter(Border.CornerRadiusProperty, new CornerRadius(3))); styles.Add(surface); var selected = new Style(x => x.OfType(type).Class(cls).Template().Name("PART_CalendarSurface").Descendant().OfType<Button>().Class("xyui-date-selected")); Set(selected, Button.BackgroundProperty, "XY.Brush.Surface.Selected"); Set(selected, Button.ForegroundProperty, "XY.Brush.Accent.Strong"); styles.Add(selected); }
    static void FocusEdge(Styles styles, Type type, string cls) { var edge = new Style(x => x.OfType(type).Class(cls).Template().Name("PART_FocusEdge")); edge.Setters.Add(new Setter(Control.OpacityProperty, 0d)); Set(edge, Border.BackgroundProperty, "XY.Brush.Accent.Strong"); styles.Add(edge); var focus = new Style(x => x.OfType(type).Class(cls).Class(":focus").Template().Name("PART_FocusEdge")); focus.Setters.Add(new Setter(Control.OpacityProperty, 1d)); styles.Add(focus); }
}
