$ErrorActionPreference='Stop'
function Fail([string]$Code,[string]$Message){throw "$Code $Message"}
function Repo([string]$Path){if($Path){return (Resolve-Path -LiteralPath $Path).Path};return (git rev-parse --show-toplevel).Trim()}
function FlightDir([string]$R){Join-Path $R '.git\xye-handoff'}
function RegPath([string]$R){Join-Path (FlightDir $R) 'task-registry.json'}
function HistPath([string]$R){Join-Path (FlightDir $R) 'task-history.jsonl'}
function Now(){(Get-Date).ToUniversalTime().ToString('o')}
function Json([string]$P){if(!(Test-Path -LiteralPath $P)){return $null};Get-Content -Raw -LiteralPath $P|ConvertFrom-Json}
function ReadReg([string]$R){$x=Json (RegPath $R);if($null -eq $x){$x=[pscustomobject]@{tasks=@()}};if($null -eq $x.tasks){$x|Add-Member NoteProperty tasks @()};$ids=@($x.tasks|%{[string]$_.TaskId});if($ids.Count -ne @($ids|select -Unique).Count){Fail TASK_REGISTRY_CORRUPT 'TaskId values are not unique.'};$state=Json (Join-Path (FlightDir $R) 'state.json');if($state -and $null -ne $state.PSObject.Properties['activeTasks']){$expected=@($x.tasks|? Status -eq 'ACTIVE'|%{[string]$_.TaskId}|sort);$actual=@($state.activeTasks|%{if($_ -is [string]){[string]$_}else{[string]$_.TaskId}}|sort);if(($expected -join "`n") -cne ($actual -join "`n")){Fail TASK_STATE_PROJECTION_MISMATCH 'state.activeTasks differs from Task Registry projection.'}};return $x}
function AtomicJson([string]$P,$Value){if(Test-Path $P -PathType Container){Fail TASK_STATE_PATH_INVALID $P};$d=Split-Path $P;New-Item -ItemType Directory -Force $d|Out-Null;$t="$P.$([guid]::NewGuid().ToString('N')).tmp";$enc=New-Object Text.UTF8Encoding -ArgumentList $false;try{[IO.File]::WriteAllText($t,($Value|ConvertTo-Json -Depth 20),$enc);Move-Item -LiteralPath $t -Destination $P -Force}finally{if(Test-Path $t -PathType Leaf){Remove-Item $t -Force}}}
function TransactionPath([string]$R){Join-Path (FlightDir $R) 'task-transaction.json'}
function AtomicText([string]$P,[string]$Text){if(Test-Path $P -PathType Container){Fail TASK_STATE_PATH_INVALID $P};$t="$P.$([guid]::NewGuid().ToString('N')).tmp";try{[IO.File]::WriteAllText($t,$Text,(New-Object Text.UTF8Encoding($false)));Move-Item -LiteralPath $t -Destination $P -Force}finally{if(Test-Path $t -PathType Leaf){Remove-Item $t -Force}}}
function Restore-TaskTransaction([string]$R,$J){$reg=RegPath $R;$hist=HistPath $R;if($J.RegistryExisted){AtomicText $reg ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($J.RegistryBefore)))}elseif(Test-Path $reg -PathType Leaf){Remove-Item $reg -Force};$old=if($J.HistoryExisted){[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($J.HistoryBefore))}else{''};$event=([ordered]@{At=(Now);Event='TRANSACTION_ROLLED_BACK';TaskId=$J.TaskId;Status='UNCHANGED';Reason='Registry/History write recovered';TransactionId=$J.Id}|ConvertTo-Json -Compress);AtomicText $hist ($old+$event+"`n");Remove-Item (TransactionPath $R) -Force -ErrorAction SilentlyContinue}
function Recover-TaskState([string]$R,[switch]$LockHeld){$p=TransactionPath $R;if(!(Test-Path $p)){return};New-Item -ItemType Directory -Force (FlightDir $R)|Out-Null;$lock=$null;if(!$LockHeld){$lock=try{[IO.File]::Open((Join-Path (FlightDir $R) 'task-transaction.lock'),[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)}catch{Fail TASK_TRANSACTION_BUSY 'Another lifecycle transaction is active.'}};try{if(Test-Path $p){$j=Json $p;Restore-TaskTransaction $R $j}}finally{if($lock){$lock.Dispose()}}}
function Save([string]$R,$Reg,$Task,[string]$Event,[string]$Reason='', [string]$Coordinator='',$Authorization=$null){
 $lock=$null;$rp=RegPath $R;$hp=HistPath $R;$jp=TransactionPath $R;$id=[guid]::NewGuid().ToString('N');$e=[ordered]@{At=(Now);Event=$Event;EventId=$id;TaskId=$Task.TaskId;Status=$Task.Status;Reason=$Reason;CloseReason=$Reason;Coordinator=$Coordinator;AuthorizationEvidence=$Authorization;TaskSnapshot=$Task};New-Item -ItemType Directory -Force (FlightDir $R)|Out-Null;$lock=try{[IO.File]::Open((Join-Path (FlightDir $R) 'task-transaction.lock'),[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)}catch{Fail TASK_TRANSACTION_BUSY 'Another lifecycle transaction is active.'};$oldReg=if(Test-Path $rp -PathType Leaf){[IO.File]::ReadAllBytes($rp)}else{$null};$oldHist=if(Test-Path $hp -PathType Leaf){[IO.File]::ReadAllBytes($hp)}else{$null};$before=[pscustomobject]@{Id=$id;TaskId=$Task.TaskId;RegistryExisted=($null -ne $oldReg);RegistryBefore=$(if($oldReg){[Convert]::ToBase64String($oldReg)}else{''});HistoryExisted=($null -ne $oldHist);HistoryBefore=$(if($oldHist){[Convert]::ToBase64String($oldHist)}else{''})}
 try{AtomicJson $jp $before;$history=if($oldHist){[Text.Encoding]::UTF8.GetString($oldHist)}else{''};AtomicText $hp ($history+($e|ConvertTo-Json -Compress -Depth 20)+"`n");AtomicJson $rp $Reg;Remove-Item $jp -Force}catch{Recover-TaskState $R -LockHeld;throw}finally{$lock.Dispose()}
}
function NormWorkspace([string]$P){([IO.Path]::GetFullPath($P)).Replace('\','/').TrimEnd('/').ToLowerInvariant()}
function NormScope([string]$P,[string]$W){$p=$P.Trim().Replace('\','/');if([IO.Path]::IsPathRooted($p)){$full=NormWorkspace $p;$base=NormWorkspace $W;if($full -eq $base){return '/'};if($full.StartsWith($base+'/')){return $full.Substring($base.Length+1)}};return ('/'+$p.TrimStart('/').TrimEnd('/')).ToLowerInvariant()}
function Values([string[]]$Items){@($Items|%{$_ -split ';'}|?{![string]::IsNullOrWhiteSpace($_)}|%{$_.Trim()})}
function Scopes([string[]]$Paths,[string]$W){@(Values $Paths|%{NormScope $_ $W}|sort -Unique)}
function Overlap([string]$A,[string]$B){$x=$A.TrimEnd('/');$y=$B.TrimEnd('/');return $x -eq $y -or $x.StartsWith($y+'/') -or $y.StartsWith($x+'/')}
function Conflict($Reg,[string[]]$Wanted,[string]$TaskId,[string]$WantedWorkspace){foreach($t in @($Reg.tasks|?{$_.Status -eq 'ACTIVE' -and $_.TaskId -ne $TaskId})){if((NormWorkspace ([string]$t.Workspace)) -ne (NormWorkspace $WantedWorkspace)){continue};foreach($a in $Wanted){foreach($b in @($t.WriteScope)){if(Overlap $a $b){return $t}}}};return $null}
function Head([string]$R){$h=git -C $R rev-parse HEAD 2>$null;if($LASTEXITCODE){Fail GIT_FAILED 'cannot read HEAD'};return ($h.Trim())}
function Assert-TaskResourcesReleased([string]$R,[string]$TaskId){$release=Json (Join-Path (FlightDir $R) 'work-release.json');if($release -and [string]$release.status -eq 'ACTIVE' -and [string]$release.taskId -ceq $TaskId){Fail TASK_WORK_RELEASE_ACTIVE 'Revoke this Task Work Release before transition.'};$locks=Json (Join-Path (FlightDir $R) 'ownership-locks.json');if($locks -and @($locks.locks|?{[string]$_.taskId -ceq $TaskId}).Count){Fail TASK_OWNERSHIP_ACTIVE 'Release this Task Ownership before transition.'}}
