$ErrorActionPreference='Stop'; $env:XYT_SKIP_GIT='1'; $root=Split-Path -Parent (Split-Path -Parent $PSScriptRoot); $pwsh=(Get-Command pwsh).Source
$module=Join-Path $root 'XYT\Runtime\xyt-runtime.ps1'; $tmp=Join-Path ([IO.Path]::GetTempPath()) ('xyt-runtime-'+[guid]::NewGuid().ToString('N')); New-Item -ItemType Directory $tmp|Out-Null
function Run([string]$name,[string]$code,[int]$expect,[hashtable]$extra=@{}){$out=Join-Path $tmp "$name.out"; $args=@('-NoProfile','-File',$module,'-Capability','P3-01','-CandidateId',"CAND-$name",'-AppCommand',$pwsh,'-AppScript',$code,'-TimeoutSeconds','2','-StdoutDrainTimeoutSeconds','1','-StderrDrainTimeoutSeconds','1','-EvidenceWriteTimeoutSeconds','1','-EvidenceRoot',$tmp); foreach($key in $extra.Keys){$args+="-$key"; if($extra[$key] -isnot [switch]){$args+=[string]$extra[$key]}}; & $pwsh @args *> $out; if($LASTEXITCODE -ne $expect){throw "$name exit=$LASTEXITCODE expected=$expect"}; $r=Get-ChildItem $tmp -Filter 'P3-01-*.json'|Where-Object Name -notlike '*.start.json'|Sort-Object LastWriteTime -Descending|Select-Object -First 1; $s=Get-ChildItem $tmp -Filter 'P3-01-*.start.json'|Sort-Object LastWriteTime -Descending|Select-Object -First 1; if(!$r -or !$s){throw "$name no evidence"}; $record=Get-Content -Raw $r.FullName|ConvertFrom-Json;$start=Get-Content -Raw $s.FullName|ConvertFrom-Json;if($start.RecordPhase -ne 'START'){throw "$name missing START record"}; foreach($field in 'StartTime','EndTime','DurationMs','CandidateId','RuntimeTestId','Status','Reason','HarnessStatus'){if([string]::IsNullOrWhiteSpace([string]$record.$field)){throw "$name missing $field"}}; $record}
try {
    $markers='【VulkanSurface】创建 Vulkan Surface 成功;逻辑设备 创建成功;Swapchain 创建成功;首帧 呈现 成功'
    $pass=Run 'pass' "Write-Output '$markers'" 0; if($pass.Status -ne 'PASS'){throw 'normal exit did not pass'}
    $fail=Run 'fail' 'Write-Output error; exit 0' 1; if($fail.Status -ne 'FAIL'){throw 'missing markers did not fail'}
    $timeout=Run 'timeout' 'Start-Sleep -Seconds 5' 1; if($timeout.Status -ne 'TIMEOUT'){throw 'timeout not captured'}
    $crash=Run 'crash' 'Write-Error crash-reason; exit 17' 1; if($crash.Status -ne 'CRASH' -or $crash.Reason -notmatch 'crash-reason'){throw 'crash stderr not captured'}
    $nogui=Run 'nogui' '' 2 @{NoGui=$true}; if($nogui.Status -ne 'BLOCKED_NO_GUI'){throw 'no-gui not classified'}
    $stdout=Run 'stdout-drain' 'Write-Output stdout' 1 @{FakeStdoutDrainTimeout=$true}; if($stdout.Status -ne 'TIMEOUT' -or $stdout.Reason -notmatch 'STDOUT_DRAIN_TIMEOUT'){throw 'stdout drain timeout not captured'}
    $stderr=Run 'stderr-drain' 'Write-Error stderr' 1 @{FakeStderrDrainTimeout=$true}; if($stderr.Status -ne 'TIMEOUT' -or $stderr.Reason -notmatch 'STDERR_DRAIN_TIMEOUT'){throw 'stderr drain timeout not captured'}
    $fault=Run 'evidence-fault' "Write-Output '$markers'" 3 @{FakeHarnessFault=$true}; if($fault.Status -ne 'EVIDENCE_FAILURE'){throw 'evidence failure not classified'}
    'XYT RUNTIME HARNESS SELFTEST: PASS'; exit 0
} finally { Remove-Item -LiteralPath $tmp -Recurse -Force -ErrorAction SilentlyContinue }
