using System.IO;
using XuanYu.Render.Abstractions;

namespace XuanYu.Core.Tests.Render.Grid;

public sealed class BlenderStyleGridTests
{
    static string Root => Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", ".."));
    static string Shader => File.ReadAllText(Path.Combine(Root, "XuanYu.Render.Vulkan", "Shaders", "editor_world_reference_grid.frag"));
    static string Bytecode => File.ReadAllText(Path.Combine(Root, "XuanYu.Render.Vulkan", "Pipeline", "ShaderBytecode.WorldReferenceGridFrag.cs"));

    [Theory]
    [InlineData(100.0, 200.0)]
    [InlineData(240.0, 400.0)]
    [InlineData(600.0, 800.0)]
    public void GridStepFriendlySeriesTest(double ideal, double expectedCoarse)
    {
        var levels = ReferenceGridScale.FromIdealSpacing(ideal);
        Assert.Equal(expectedCoarse, levels.CoarseSpacing);
        Assert.Equal(2.0, levels.CoarseSpacing / levels.FineSpacing);
    }

    [Fact]
    public void GridLodTransitionContinuityTest()
    {
        var levels = ReferenceGridScale.FromIdealSpacing(150.0);
        Assert.InRange(levels.FineWeight, 0.0, 1.0);
        Assert.InRange(levels.CoarseWeight, 0.0, 1.0);
        Assert.Equal(1.0, levels.FineWeight + levels.CoarseWeight, 6);
    }

    [Fact]
    public void MinorGridFadeBeforeMajorSwitchTest()
    {
        Assert.Contains("fineWeight", Shader);
        Assert.Contains("coarseWeight", Shader);
        Assert.Contains("smoothstep", Shader);
    }

    [Fact]
    public void MajorGridPersistsAcrossZoomTest()
    {
        var levels = ReferenceGridScale.FromIdealSpacing(190.0);
        Assert.True(levels.CoarseWeight > 0.0);
        Assert.True(levels.CoarseSpacing > levels.FineSpacing);
    }

    [Fact]
    public void Adjacent_grid_levels_are_nested()
    {
        foreach (var ideal in new[] { 100.0, 150.0, 240.0, 600.0, 10_000.0, 1_000_000.0 })
        {
            var levels = ReferenceGridScale.FromIdealSpacing(ideal);
            Assert.Equal(0.0, levels.CoarseSpacing % levels.FineSpacing, 6);
        }
    }

    [Fact]
    public void Last_grid_level_persists()
    {
        var levels = ReferenceGridScale.FromIdealSpacing(ReferenceGridScale.MaxSpacing);
        Assert.Equal(ReferenceGridScale.MaxSpacing, levels.FineSpacing);
        Assert.Equal(levels.FineSpacing, levels.CoarseSpacing);
        Assert.Equal(1.0, levels.FineWeight);
        Assert.Equal(0.0, levels.CoarseWeight);
    }

    [Fact]
    public void NoHardVisibilityPopTest()
    {
        Assert.DoesNotContain("coarseContribution > fineContribution ?", Shader);
        Assert.Contains("fineContribution + coarseContribution", Shader);
    }

    [Fact]
    public void PerspectiveGridContractTest()
    {
        var levels = ReferenceGridScale.Compute(new ViewportMetricScale(2.0, 8.0, 1.0));
        Assert.True(levels.FineSpacing >= ReferenceGridScale.MinSpacing);
    }

    [Fact]
    public void OrthographicGridContractTest()
    {
        var levels = ReferenceGridScale.Compute(new ViewportMetricScale(0.25, 0.25, 1.0));
        Assert.Equal(ReferenceGridScale.MinSpacing, levels.FineSpacing);
    }

    [Fact]
    public void GridShaderBytecodeSyncTest()
    {
        Assert.Contains("AUTO-GENERATED by glslc -O from editor_world_reference_grid.frag", Bytecode);
        Assert.Contains("ShaderBytecodeWorldReferenceGridFrag", Bytecode);
        Assert.Contains("pc.gridState", Shader);
    }
}
