<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>XuanYu.Editor.Win</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XuanYu.Core\XuanYu.Core.csproj" />
  </ItemGroup>
</Project>
