function Revoke($R,$Release,[string]$Why){$Release.status='REVOKED';$Release|Add-Member NoteProperty revokedReason $Why -Force;$Release|Add-Member NoteProperty revokedAt ((Get-Date).ToUniversalTime().ToString('o')) -Force;Write-Json (JsonPath $R 'work-release.json') $Release;Fail WRITE_DENIED $Why}
function Validate-Release($R,[string]$Token,[string]$Lane,[string]$Task,[string[]]$Files){
    $x=Read-Json (JsonPath $R 'work-release.json'); if(!$x -or $x.token -ne $Token -or $x.status -ne 'ACTIVE'){Fail WRITE_DENIED 'Missing or inactive Work Release Token.'}
    if($x.laneId -ne $Lane){Revoke $R $x 'Lane Identity Mismatch.'}; if($x.taskId -ne $Task){Revoke $R $x 'Task Identity Mismatch.'}
    $s=State $R; $c=Current $R; if(!$s.active -or [string]::IsNullOrWhiteSpace([string]$s.coordinatorScope) -or [string]$s.coordinatorScope -ne 'xye' -or $s.mode -match 'blocked|stopped'){Revoke $R $x 'Coordinator BLOCKED.'}
    if($c.Head -ne $x.baselineHead -or $c.Head -ne $s.baselineHead){Revoke $R $x 'Baseline HEAD changed.'}
    if((Fingerprint $R @($x.ownershipSet)) -ne $x.candidateFingerprint){Revoke $R $x 'Candidate Fingerprint changed.'}
    if((UnknownDirty $R).Count){Revoke $R $x 'UnknownDirty > 0.'}; if(!(VersionEvent $R $x.versionEventId)){Revoke $R $x 'Version Event missing.'}
    foreach($f in $Files){if(@($x.ownershipSet) -notcontains $f){Fail OWNERSHIP_CONFLICT "File is outside Ownership Set: $f"}}
    $x
}
function Revoke-WorkRelease([string]$R,[string]$EvidenceUrl){$lock=Lock (JsonPath $R 'work-release.issue.lock');try{$x=Read-Json (JsonPath $R 'work-release.json');if(!$x -or [string]$x.status -ne 'ACTIVE'){Fail RELEASE_NOT_ACTIVE 'No active release to revoke.'};$c=Current $R;$auth=Assert-OwnerAuthorization $R $EvidenceUrl 'work-release-revoke' ([string]$x.taskId) 'REVOKE' $c.Head;Consume-OwnerAuthorization $R $auth;$x.status='REVOKED';$x.revokedReason='Owner-authorized revocation';$x.revokedAt=(Get-Date).ToUniversalTime().ToString('o');Write-Json (JsonPath $R 'work-release.json') $x;'WORK RELEASE REVOKED'}finally{$lock.Dispose()}}
function Claim-Ownership($R,[string]$Token,[string]$Lane,[string]$Task,[string[]]$Files){$x=Validate-Release $R $Token $Lane $Task $Files; $p=JsonPath $R 'ownership-locks.json'; $h=Lock (JsonPath $R 'ownership-locks.lock'); try{$o=Read-Json $p; if(!$o){$o=[pscustomobject]@{schema='XYT-OM/1';locks=@()}}; foreach($f in $Files){$old=@($o.locks)|? path -eq $f; if($old -and $old.laneId -ne $Lane){Fail OWNERSHIP_CONFLICT "Already owned by $($old.laneId): $f"}}; foreach($f in $Files){$o.locks=@(@($o.locks)|? path -ne $f)+[pscustomobject]@{path=$f;laneId=$Lane;taskId=$Task;token=$Token}}; Write-Json $p $o; $x}catch{throw}finally{$h.Dispose()}}
