<#
.SYNOPSIS
    在 spirv-val 通过后，将 basic_3d.vert.spv / basic_3d.frag.spv
    写入 CompiledShaders.cs，使 Scene3D 可被手动触发。

.DESCRIPTION
    执行前必须满足：
    1. basic_3d.vert.spv 和 basic_3d.frag.spv 存在。
    2. spirv-val 可执行。
    3. 两个 .spv 通过 spirv-val 验证。
    4. 两个 .spv SPIR-V 魔数正确（0x07230203）。

    本脚本会独立执行 spirv-val（不依赖用户已执行过 validate）。

.NOTES
    从仓库根目录执行：
    powershell -ExecutionPolicy Bypass -File tools/shaders/embed_basic_3d_shaders.ps1
#>

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
Push-Location $repoRoot

try
{
    # 1. 定位文件路径
    $compiledDir = Join-Path $repoRoot "FluidWarfare.Render.Vulkan\Shaders\Compiled"
    $vertSpv = Join-Path $compiledDir "basic_3d.vert.spv"
    $fragSpv = Join-Path $compiledDir "basic_3d.frag.spv"
    $outputFile = Join-Path $repoRoot "FluidWarfare.Render.Vulkan\Shaders\CompiledShaders.cs"

    # 2. 检查 .spv 文件是否存在
    $missing = @()
    if (-not (Test-Path $vertSpv)) { $missing += "basic_3d.vert.spv" }
    if (-not (Test-Path $fragSpv)) { $missing += "basic_3d.frag.spv" }
    if ($missing.Count -gt 0)
    {
        Write-Host "错误：未找到以下文件：" -ForegroundColor Red
        foreach ($m in $missing) { Write-Host "  - $m" -ForegroundColor Red }
        Write-Host "请先执行：" -ForegroundColor Yellow
        Write-Host "  powershell -ExecutionPolicy Bypass -File tools/shaders/compile_basic_3d.ps1" -ForegroundColor Yellow
        exit 1
    }

    # 3. 检查 spirv-val 并对 .spv 执行验证
    $spirvVal = Get-Command "spirv-val" -ErrorAction SilentlyContinue
    if (-not $spirvVal)
    {
        Write-Host "错误：未检测到 spirv-val。" -ForegroundColor Red
        Write-Host "请安装 Vulkan SDK 或将 spirv-val 所在目录加入 PATH。" -ForegroundColor Yellow
        exit 1
    }

    Write-Host "检测到 spirv-val：$($spirvVal.Source)" -ForegroundColor Green

    foreach ($spv in @($vertSpv, $fragSpv))
    {
        $name = Split-Path -Leaf $spv
        Write-Host "验证 $name ..." -ForegroundColor Cyan
        & $spirvVal.Source $spv
        if ($LASTEXITCODE -ne 0)
        {
            Write-Host "错误：$name 验证未通过。" -ForegroundColor Red
            exit 1
        }
        Write-Host "  spirv-val 通过：$name" -ForegroundColor Green
    }

    # 4. 检查 SPIR-V 魔数
    $magicBytes = [byte[]]@(0x03, 0x02, 0x23, 0x07)
    foreach ($spv in @($vertSpv, $fragSpv))
    {
        $name = Split-Path -Leaf $spv
        $header = [System.IO.File]::ReadAllBytes($spv) | Select-Object -First 4
        $ok = $true
        for ($i = 0; $i -lt 4; $i++) { if ($header[$i] -ne $magicBytes[$i]) { $ok = $false; break } }
        if (-not $ok)
        {
            Write-Host "错误：$name 不是有效 SPIR-V 文件：魔数不匹配。" -ForegroundColor Red
            exit 1
        }
        Write-Host "  魔数正确：$name" -ForegroundColor Green
    }

    # 5. 读取字节并转换为 uint 数组
    function Convert-SpvToUintArray($path)
    {
        $bytes = [System.IO.File]::ReadAllBytes($path)
        $words = [System.Collections.Generic.List[uint32]]::new()
        for ($i = 0; $i -lt $bytes.Length; $i += 4)
        {
            $w = [uint32]($bytes[$i]) -bor
                 ([uint32]($bytes[$i+1]) -shl 8) -bor
                 ([uint32]($bytes[$i+2]) -shl 16) -bor
                 ([uint32]($bytes[$i+3]) -shl 24)
            $words.Add($w)
        }
        return $words
    }

    $vertWords = Convert-SpvToUintArray $vertSpv
    $fragWords = Convert-SpvToUintArray $fragSpv

    Write-Host "  顶点着色器：$($vertWords.Count) 个 uint32" -ForegroundColor Gray
    Write-Host "  片段着色器：$($fragWords.Count) 个 uint32" -ForegroundColor Gray

    # 6. 格式化 uint 数组
    function Format-UintArray($words, $indent)
    {
        $lines = @()
        $line = "$indent"
        for ($i = 0; $i -lt $words.Count; $i++)
        {
            $wordStr = "0x$('{0:X8}' -f $words[$i])"
            if ($line.Length + $wordStr.Length + 2 -gt 120)
            {
                $lines += $line.TrimEnd(', ')
                $line = "$indent$wordStr, "
            }
            else
            {
                if ($line -eq "$indent") { $line += "$wordStr, " }
                else { $line += "$wordStr, " }
            }
        }
        if ($line -ne "$indent") { $lines += $line.TrimEnd(', ') }
        return $lines
    }

    $vertFormatted = Format-UintArray $vertWords "        " -join "`n"
    $fragFormatted = Format-UintArray $fragWords "        "

    # 7. 生成 CompiledShaders.cs
    $content = @"
// <auto-generated>
// 由 tools/shaders/embed_basic_3d_shaders.ps1 在 spirv-val 通过后生成。
// 不要手工编辑。
// </auto-generated>
namespace FluidWarfare.Render.Vulkan.Shaders;

internal static class CompiledShaders
{
    public static uint[] Basic3dVert { get; internal set; } = new uint[]
    {
$vertFormatted
    };

    public static uint[] Basic3dFrag { get; internal set; } = new uint[]
    {
$fragFormatted
    };

    public static bool Basic3dVertexValidatedBySpirvVal { get; internal set; } = true;

    public static bool Basic3dFragmentValidatedBySpirvVal { get; internal set; } = true;

    public static bool HasValidatedBasic3dShaders =>
        Basic3dVert.Length > 0 &&
        Basic3dFrag.Length > 0 &&
        Basic3dVertexValidatedBySpirvVal &&
        Basic3dFragmentValidatedBySpirvVal;
}
"@

    [System.IO.File]::WriteAllText($outputFile, $content, [System.Text.UTF8Encoding]::new($false))
    Write-Host ""
    Write-Host "生成完成：$outputFile" -ForegroundColor Green
    Write-Host "  Basic3dVert: $($vertWords.Count) 个 uint32" -ForegroundColor Green
    Write-Host "  Basic3dFrag: $($fragWords.Count) 个 uint32" -ForegroundColor Green
    Write-Host "  HasValidatedBasic3dShaders: true" -ForegroundColor Green
}
finally
{
    Pop-Location
}
