using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.Controls.Documents;
using Avalonia.Controls.Presenters;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.Templates;
using Avalonia.Input;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.VisualTree;
using XYUI.Avalonia.Vector;

namespace XYUI.Avalonia.Controls;

public sealed record XYTocSection(string Id, string Label, int Level = 1, string? ParentId = null, bool IsEnabled = true);
public sealed class XYTableOfContentsState
{
    public IReadOnlyList<XYTocSection> Sections { get; } public string? CurrentSectionId { get; private set; } public event EventHandler? Changed;
    public XYTableOfContentsState(IEnumerable<XYTocSection> sections, string? current = null) { Sections = sections.Where(s => s.Level is 1 or 2).ToArray(); CurrentSectionId = current ?? Sections.FirstOrDefault()?.Id; }
    public bool Commit(string id) { if (CurrentSectionId == id || !Sections.Any(s => s.Id == id && s.IsEnabled)) return false; CurrentSectionId = id; Changed?.Invoke(this, EventArgs.Empty); return true; }
}
public sealed class XYTocSectionRequest : EventArgs
{
    public XYTocSection Section { get; } public bool IsAccepted { get; private set; } public bool IsRejected { get; private set; }
    public XYTocSectionRequest(XYTocSection section) => Section = section;
    public void Accept() { if (!IsRejected) IsAccepted = true; } public void Reject() { IsAccepted = false; IsRejected = true; }
}
public enum XYTableOfContentsVariant { Hierarchical, Compact }
public sealed class XYTocItem : XYButton
{
    public XYTocItem() { Classes.Remove("xyui-button"); Classes.Remove("xyui-button-primary"); Classes.Remove("xyui-button-secondary"); Classes.Remove("xyui-button-danger"); Classes.Add("xyui-toc-button"); FocusAdorner = null; }
}
internal static class XyuiTocItemChrome
{
    internal static FuncControlTemplate<XYTocItem> Create() => new((control, _) =>
    {
        var root = new Border { ClipToBounds = true };
        root[!Border.BackgroundProperty] = control[!TemplatedControl.BackgroundProperty]; root[!Border.BorderBrushProperty] = control[!TemplatedControl.BorderBrushProperty]; root[!Border.BorderThicknessProperty] = control[!TemplatedControl.BorderThicknessProperty]; root[!Border.CornerRadiusProperty] = control[!TemplatedControl.CornerRadiusProperty];
        var presenter = new ContentPresenter { HorizontalAlignment = HorizontalAlignment.Stretch, VerticalAlignment = VerticalAlignment.Center };
        presenter[!ContentPresenter.PaddingProperty] = control[!TemplatedControl.PaddingProperty]; presenter[!ContentPresenter.ContentProperty] = control[!Button.ContentProperty]; presenter[!ContentPresenter.HorizontalContentAlignmentProperty] = control[!Button.HorizontalContentAlignmentProperty]; presenter[!ContentPresenter.VerticalContentAlignmentProperty] = control[!Button.VerticalContentAlignmentProperty]; presenter[!TextElement.ForegroundProperty] = control[!TemplatedControl.ForegroundProperty]; root.Child = presenter; return root;
    });
}
public sealed partial class XYTableOfContents : Border
{
    readonly Border _surface = new() { Classes = { "xyui-toc-surface" } }; readonly Grid _grid = new();
    readonly XYMenu _menu = new() { Classes = { "xyui-toc-menu" } }; readonly Border _popupPanel = new() { Classes = { "xyui-toc-popup-panel" } }; readonly Popup _popup = new() { Placement = PlacementMode.Bottom, IsLightDismissEnabled = true };
    readonly Dictionary<XYTocItem, string> _menuIds = new(); IActivatableLifetime? _applicationLifetime; WindowBase? _hostWindow;
    public XYTableOfContentsState State { get; } public XYTableOfContentsVariant Variant { get; } public XYMenu Menu => _menu; public Popup Popup => _popup; public string? CurrentSectionId => State.CurrentSectionId;
    public event EventHandler<XYTocSectionRequest>? SectionRequested; public event EventHandler<string>? SectionChanged;
    public XYTableOfContents(XYTableOfContentsState state, XYTableOfContentsVariant variant = XYTableOfContentsVariant.Hierarchical) { State = state; Variant = variant; State.Changed += (_, _) => Refresh(); Classes.Add("xyui-table-of-contents"); _popup.Child = _popupPanel; _menu.Closed += (_, _) => _popup.IsOpen = false; Child = _surface; Refresh(); }
    public XYTableOfContents(IEnumerable<XYTocSection> sections, XYTableOfContentsVariant variant = XYTableOfContentsVariant.Hierarchical) : this(new XYTableOfContentsState(sections), variant) { }
    void Refresh() { _grid.Children.Clear(); _grid.RowDefinitions.Clear(); if (Variant == XYTableOfContentsVariant.Compact) { _grid.Children.Add(BuildCompact()); } else { _grid.RowDefinitions.Add(new RowDefinition(GridLength.Auto)); _grid.Children.Add(new TextBlock { Text = "本页目录", Classes = { "xyui-toc-header" }, VerticalAlignment = VerticalAlignment.Center }); _grid.RowDefinitions.Add(new RowDefinition(1, GridUnitType.Star)); var rows = BuildDesktopRows(); Grid.SetRow(rows, 1); _grid.Children.Add(rows); } _surface.Child = _grid; }
    Control BuildDesktopRows() { var host = new StackPanel { Classes = { "xyui-toc-section-host" } }; var parents = State.Sections.Where(s => s.Level == 1).ToArray(); var children = State.Sections.Where(s => s.Level == 2).ToArray(); var rendered = new HashSet<string>(); foreach (var parent in parents) { host.Children.Add(BuildDesktopItem(parent)); var group = children.Where(s => s.ParentId == parent.Id).ToArray(); if (group.Length > 0) { host.Children.Add(BuildChildGroup(group)); foreach (var child in group) rendered.Add(child.Id); } } foreach (var orphan in children.Where(s => !rendered.Contains(s.Id))) host.Children.Add(BuildDesktopItem(orphan, true)); return host; }
    Control BuildChildGroup(IReadOnlyList<XYTocSection> children) { var group = new Grid { ColumnDefinitions = new ColumnDefinitions("14,1,*"), Classes = { "xyui-toc-child-group" } }; var guide = new Border { Classes = { "xyui-toc-level-guide" }, VerticalAlignment = VerticalAlignment.Stretch }; var host = new StackPanel { Classes = { "xyui-toc-child-host" }, Margin = new Thickness(8, 0, 0, 0) }; foreach (var child in children) host.Children.Add(BuildDesktopItem(child, true)); Grid.SetColumn(guide, 1); Grid.SetColumn(host, 2); group.Children.Add(guide); group.Children.Add(host); return group; }
    XYTocItem BuildDesktopItem(XYTocSection section, bool isChild = false) { var parentActive = !isChild && State.Sections.Any(x => x.ParentId == section.Id && x.Id == CurrentSectionId); var current = section.Id == CurrentSectionId; var grid = new Grid { ColumnDefinitions = new ColumnDefinitions("3,*"), Height = 30, VerticalAlignment = VerticalAlignment.Center }; var accent = new Border { Classes = { "xyui-toc-current-accent" }, IsVisible = current }; var text = new TextBlock { Text = section.Label, VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(isChild ? 6 : 0, 0, 0, 0) }; Grid.SetColumn(text, 1); grid.Children.Add(accent); grid.Children.Add(text); var item = new XYTocItem { Content = grid, Height = 30, HorizontalAlignment = HorizontalAlignment.Stretch, HorizontalContentAlignment = HorizontalAlignment.Stretch, IsEnabled = section.IsEnabled }; item.Classes.Add("xyui-toc-item"); item.Classes.Add(isChild ? "xyui-toc-child" : "xyui-toc-parent"); if (current) item.Classes.Add("xyui-toc-current"); if (parentActive) item.Classes.Add("xyui-toc-parent-active"); item.Click += (_, _) => SelectSection(section.Id); return item; }
    XYButton BuildCompact() { var current = State.Sections.FirstOrDefault(s => s.Id == CurrentSectionId); var parent = current?.ParentId is null ? null : State.Sections.FirstOrDefault(s => s.Id == current.ParentId); var path = parent is null ? current?.Label ?? "选择章节" : $"{parent.Label} / {current!.Label}"; var grid = new Grid { ColumnDefinitions = new ColumnDefinitions("Auto,*,Auto"), VerticalAlignment = VerticalAlignment.Center }; var label = new TextBlock { Text = "本页目录", Classes = { "xyui-toc-trigger-label" }, VerticalAlignment = VerticalAlignment.Center }; var value = new TextBlock { Text = path, Classes = { "xyui-toc-trigger-current" }, TextTrimming = TextTrimming.CharacterEllipsis, VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(12, 0, 0, 0) }; var chevron = new XYIcon { Icon = XyuiVectorIcon.ChevronDown, Size = XyuiIconSize.Small, VerticalAlignment = VerticalAlignment.Center }; Grid.SetColumn(value, 1); Grid.SetColumn(chevron, 2); grid.Children.Add(label); grid.Children.Add(value); grid.Children.Add(chevron); var button = new XYButton { Content = grid, Height = 34, Width = 256, HorizontalAlignment = HorizontalAlignment.Stretch, HorizontalContentAlignment = HorizontalAlignment.Stretch, Variant = XyuiButtonVariant.Secondary, Classes = { "xyui-toc-trigger" } }; button.Click += (_, _) => OpenCompactPopup(button); return button; }
    void OpenCompactPopup(Control trigger) { _menuIds.Clear(); var host = new StackPanel { Classes = { "xyui-toc-popup-host" } }; var parents = State.Sections.Where(s => s.Level == 1).ToArray(); var children = State.Sections.Where(s => s.Level == 2).ToArray(); var rendered = new HashSet<string>(); foreach (var parent in parents) { host.Children.Add(BuildPopupItem(parent)); var group = children.Where(s => s.ParentId == parent.Id).ToArray(); if (group.Length > 0) { host.Children.Add(BuildPopupChildGroup(group)); foreach (var child in group) rendered.Add(child.Id); } } foreach (var orphan in children.Where(s => !rendered.Contains(s.Id))) host.Children.Add(BuildPopupItem(orphan, true)); _menu.Items = []; _popupPanel.Child = host; _popup.PlacementTarget = trigger; var width = trigger.Bounds.Width > 0 ? trigger.Bounds.Width : trigger.Width; _popup.Width = Math.Max(1, width); _popup.IsOpen = true; }
    XYTocItem BuildPopupItem(XYTocSection section, bool isChild = false) { var current = section.Id == CurrentSectionId; var parentActive = !isChild && State.Sections.Any(x => x.ParentId == section.Id && x.Id == CurrentSectionId); var grid = new Grid { ColumnDefinitions = new ColumnDefinitions("3,*,24"), Height = 30 }; var accent = new Border { Classes = { "xyui-toc-current-accent" }, IsVisible = current }; var text = new TextBlock { Text = section.Label, VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(isChild ? 6 : 0, 0, 0, 0) }; var check = new XYIcon { Icon = XyuiVectorIcon.Check, Classes = { "xyui-toc-menu-check" }, IsVisible = current, HorizontalAlignment = HorizontalAlignment.Right, VerticalAlignment = VerticalAlignment.Center }; Grid.SetColumn(text, 1); Grid.SetColumn(check, 2); grid.Children.Add(accent); grid.Children.Add(text); grid.Children.Add(check); var item = new XYTocItem { Content = grid, Height = 30, HorizontalAlignment = HorizontalAlignment.Stretch, HorizontalContentAlignment = HorizontalAlignment.Stretch, IsEnabled = section.IsEnabled }; _menuIds[item] = section.Id; item.Classes.Add("xyui-toc-menu-item"); item.Classes.Add(isChild ? "xyui-toc-menu-child" : "xyui-toc-menu-parent"); if (current) item.Classes.Add("xyui-toc-current"); if (parentActive) item.Classes.Add("xyui-toc-parent-active"); item.Click += (_, _) => { SelectSection(section.Id); CloseCompactPopup(); }; return item; }
    Control BuildPopupChildGroup(IReadOnlyList<XYTocSection> children) { var group = new Grid { ColumnDefinitions = new ColumnDefinitions("14,1,*"), Classes = { "xyui-toc-child-group" } }; var guide = new Border { Classes = { "xyui-toc-level-guide" }, VerticalAlignment = VerticalAlignment.Stretch }; var host = new StackPanel { Classes = { "xyui-toc-child-host" }, Margin = new Thickness(8, 0, 0, 0) }; foreach (var child in children) host.Children.Add(BuildPopupItem(child, true)); Grid.SetColumn(guide, 1); Grid.SetColumn(host, 2); group.Children.Add(guide); group.Children.Add(host); return group; }
    public void SelectSection(string id) { var section = State.Sections.FirstOrDefault(s => s.Id == id); if (section is null || !section.IsEnabled || section.Id == CurrentSectionId) return; var request = new XYTocSectionRequest(section); SectionRequested?.Invoke(this, request); if (request.IsAccepted && State.Commit(id)) SectionChanged?.Invoke(this, id); }
    public void CommitCurrentSection(string id) => State.Commit(id); public void CloseCompactPopup() { _menu.Close(); _popup.IsOpen = false; }
    protected override void OnAttachedToVisualTree(VisualTreeAttachmentEventArgs e) { base.OnAttachedToVisualTree(e); _applicationLifetime = Application.Current?.ApplicationLifetime as IActivatableLifetime; if (_applicationLifetime is not null) _applicationLifetime.Deactivated += OnApplicationDeactivated; _hostWindow = e.RootVisual as WindowBase; if (_hostWindow is not null) { _hostWindow.Deactivated += OnHostWindowDeactivated; _hostWindow.Closed += OnHostWindowClosed; } }
    protected override void OnDetachedFromVisualTree(VisualTreeAttachmentEventArgs e) { CloseCompactPopup(); if (_applicationLifetime is not null) _applicationLifetime.Deactivated -= OnApplicationDeactivated; if (_hostWindow is not null) { _hostWindow.Deactivated -= OnHostWindowDeactivated; _hostWindow.Closed -= OnHostWindowClosed; } _applicationLifetime = null; _hostWindow = null; base.OnDetachedFromVisualTree(e); }
    void OnApplicationDeactivated(object? sender, ActivatedEventArgs e) => CloseCompactPopup(); void OnHostWindowDeactivated(object? sender, EventArgs e) => CloseCompactPopup(); void OnHostWindowClosed(object? sender, EventArgs e) => CloseCompactPopup();
}
