[CmdletBinding()]
param([string]$RepositoryRoot=(Get-Location).Path,[string]$WaveId,[ValidateSet('xye','integration','governance')][string]$Scope,[string]$BaselineHead,[string]$ExpectedBranch,[string]$AuthorizationEvidenceUrl)
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'authority-auth.ps1')
function Wave-Fail([string]$Code,[string]$Reason){throw "WAVE_INIT_DENIED: $Code / $Reason"}
function Wave-Dir([string]$R){Join-Path $R '.git/xye-handoff'}
function Wave-Path([string]$R,[string]$N){Join-Path (Wave-Dir $R) $N}
function Wave-Read([string]$P){if(Test-Path $P -PathType Leaf){Get-Content -Raw -LiteralPath $P|ConvertFrom-Json}else{$null}}
function Wave-Text([string]$P,[string]$Text){if(Test-Path $P -PathType Container){throw "STATE_PATH_INVALID: $P"};$tmp="$P.$([guid]::NewGuid().ToString('N')).tmp";[IO.File]::WriteAllText($tmp,$Text,(New-Object Text.UTF8Encoding($false)));Move-Item -LiteralPath $tmp -Destination $P -Force}
function Wave-Append([string]$P,[string]$Text){$old=if(Test-Path $P -PathType Leaf){Get-Content -Raw -LiteralPath $P}else{''};Wave-Text $P ($old+$Text+"`n")}
function Wave-AtomicJson([string]$P,$Value){Wave-Text $P ($Value|ConvertTo-Json -Depth 20)}
function Wave-Journal([string]$R){Wave-Path $R 'wave-init-transaction.json'}
function Wave-Restore([string]$R,$Journal){foreach($entry in $Journal.Files){if($entry.Existed){Wave-Text $entry.Path ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($entry.Content)))}elseif(Test-Path $entry.Path -PathType Leaf){Remove-Item $entry.Path -Force}};$history=Wave-Path $R 'wave-history.jsonl';$event=([ordered]@{At=[datetime]::UtcNow.ToString('o');Event='WAVE_INIT_ROLLED_BACK';WaveId=$Journal.WaveId;TransactionId=$Journal.Id;Reason='Atomic install failed; prior files restored'}|ConvertTo-Json -Compress);Wave-Append $history $event;Remove-Item (Wave-Journal $R) -Force -ErrorAction SilentlyContinue}
function Recover-WaveInit([string]$R,[switch]$LockHeld){$jp=Wave-Journal $R;if(Test-Path $jp){Wave-Restore $R (Wave-Read $jp)}}
function Install-Wave([string]$R,[string]$Id,[string]$Scope,[string]$Head,[string]$Branch,$Authorization){
 $dir=Wave-Dir $R;$targets=@('state.json','work-release.json','ownership-locks.json')|%{Wave-Path $R $_};$state=[ordered]@{schemaVersion='XYE-HANDOFF/3';authorityModel='R3-LANE-COORDINATOR';active=$true;mode='development';coordinatorScope=$Scope;waveId=$Id;baselineHead=$Head;branch=$Branch;initializedAt=[datetime]::UtcNow.ToString('o')};$release=[ordered]@{schema='XYT-WR/1';status='IDLE';coordinatorScope=$Scope;waveId=$Id;baselineHead=$Head;token='';taskId='';laneId='';ownershipSet=@();initializedAt=[datetime]::UtcNow.ToString('o')};$locks=[ordered]@{schema='XYT-OM/1';coordinatorScope=$Scope;waveId=$Id;locks=@();initializedAt=[datetime]::UtcNow.ToString('o')}
 $values=@(($state|ConvertTo-Json -Depth 12),($release|ConvertTo-Json -Depth 12),($locks|ConvertTo-Json -Depth 12));$files=@();for($i=0;$i -lt $targets.Count;$i++){$old=if(Test-Path $targets[$i] -PathType Leaf){[IO.File]::ReadAllBytes($targets[$i])}else{$null};$files+=,[pscustomobject]@{Path=$targets[$i];Existed=($null -ne $old);Content=$(if($old){[Convert]::ToBase64String($old)}else{''});Value=$values[$i]}}
 $history=Wave-Path $R 'wave-history.jsonl';$idTx=[guid]::NewGuid().ToString('N');$journal=[pscustomobject]@{Id=$idTx;WaveId=$Id;Files=@($files|%{[pscustomobject]@{Path=$_.Path;Existed=$_.Existed;Content=$_.Content}})};Wave-AtomicJson (Wave-Journal $R) $journal
 $priorState=Wave-Read (Wave-Path $R 'state.json');try{for($i=0;$i -lt $files.Count;$i++){Wave-Text $files[$i].Path $files[$i].Value};$event=([ordered]@{At=[datetime]::UtcNow.ToString('o');Event='WAVE_INITIALIZED';WaveId=$Id;Scope=$Scope;BaselineHead=$Head;Branch=$Branch;PreviousState=$priorState;Authorization=$Authorization;TransactionId=$idTx}|ConvertTo-Json -Compress -Depth 12);Wave-Append $history $event;Remove-Item (Wave-Journal $R) -Force}catch{Wave-Restore $R $journal;throw}
 [pscustomobject]@{Status='INITIALIZED';WaveId=$Id;Scope=$Scope;BaselineHead=$Head;Branch=$Branch}
}
function Initialize-Wave([string]$R,[string]$Id,[string]$Scope,[string]$Head,[string]$Branch,[string]$EvidenceUrl){
 $R=(Resolve-Path -LiteralPath $R).Path;if([string]::IsNullOrWhiteSpace($Id)-or[string]::IsNullOrWhiteSpace($Scope)){Wave-Fail INVALID_INPUT 'WaveId and Scope are required.'};$current=(git -C $R rev-parse HEAD).Trim();$branchNow=(git -C $R branch --show-current).Trim();if($current -cne $Head -or $branchNow -cne $Branch){Wave-Fail BASELINE_MISMATCH 'HEAD or branch differs.'};if(@(git -C $R status --porcelain=v1 --untracked-files=all).Count){Wave-Fail DIRTY_WORKTREE 'Workspace must be clean.'};$auth=Assert-OwnerAuthorization $R $EvidenceUrl 'wave-init' $Id $Scope $Head;$lock=$null;$taskLock=$null;New-Item -ItemType Directory -Force (Wave-Dir $R)|Out-Null
 try{$lock=[IO.File]::Open((Wave-Path $R 'coordinator-operation.lock'),[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None);$taskLock=[IO.File]::Open((Wave-Path $R 'task-lifecycle.lock'),[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)}catch{if($lock){$lock.Dispose()};Wave-Fail WAVE_INIT_BUSY 'Another lifecycle operation is active.'}
 try{Recover-WaveInit $R -LockHeld;$current=(git -C $R rev-parse HEAD).Trim();$branchNow=(git -C $R branch --show-current).Trim();if($current -cne $Head -or $branchNow -cne $Branch -or [string]::IsNullOrWhiteSpace($Id)){Wave-Fail BASELINE_MISMATCH 'HEAD, branch, or WaveId differs.'};if(@(git -C $R status --porcelain=v1 --untracked-files=all).Count){Wave-Fail DIRTY_WORKTREE 'Workspace must be clean.'}
  $state=Wave-Read (Wave-Path $R 'state.json');if($state -and [bool]$state.active){Wave-Fail ACTIVE_WAVE_EXISTS 'Refusing to replace an active Wave.'};$registry=Wave-Read (Wave-Path $R 'task-registry.json');$tasks=if($registry -and $null -ne $registry.PSObject.Properties['tasks']){@($registry.tasks)}else{@()};if($state -and $null -ne $state.PSObject.Properties['activeTasks']){$projected=@($state.activeTasks|%{if($_ -is [string]){[string]$_}else{[string]$_.TaskId}}|Sort-Object);$authoritative=@($tasks|? Status -eq 'ACTIVE'|%{[string]$_.TaskId}|Sort-Object);if(($projected -join "`n") -cne ($authoritative -join "`n")){Wave-Fail TASK_STATE_PROJECTION_MISMATCH 'state.activeTasks differs from Task Registry projection.'}};$open=@($tasks|%{@($_.ExpectedDependencies)}|?{[string]$_ -match 'OPEN'});if($open.Count){Wave-Fail OPEN_DEPENDENCIES 'Open dependencies remain.'};if($tasks.Count){Wave-Fail TASKS_UNRESOLVED 'Task Registry is not empty.'}
  if(Test-Path (Wave-Path $R 'candidate-freeze.json')){Wave-Fail CANDIDATE_EXISTS 'Existing Candidate must be reconciled separately.'};$release=Wave-Read (Wave-Path $R 'work-release.json');if($release -and [string]$release.status -ne 'IDLE'){Wave-Fail ACTIVE_WORK_RELEASE 'Work Release is not idle.'};$ownership=Wave-Read (Wave-Path $R 'ownership-locks.json');if($ownership -and @($ownership.locks).Count){Wave-Fail OWNERSHIP_REMAINS 'Ownership locks remain.'};if(Test-Path (Wave-Path $R 'commit-mutex.json')){Wave-Fail COMMIT_MUTEX_HELD 'Commit Mutex remains.'}
  Consume-OwnerAuthorization $R $auth;Install-Wave $R $Id $Scope $Head $Branch $auth
 }finally{if($taskLock){$taskLock.Dispose()};if($lock){$lock.Dispose()}}
}
if($MyInvocation.InvocationName -ne '.') {try{Initialize-Wave $RepositoryRoot $WaveId $Scope $BaselineHead $ExpectedBranch $AuthorizationEvidenceUrl|ConvertTo-Json -Depth 12}catch{Write-Error $_.Exception.Message;exit 1}}
