#version 450
#define active activeIndex
// Blender 风格透明导航 Gizmo：不绘制底板，直接与 viewport 融合。
// TRANSPARENT_BACKGROUND / Z-Up / 六端点。
// POSITIVE_RADIUS_DIP = 8.5; NEGATIVE_RADIUS_DIP = 7.5; ENDPOINT_COUNT = 6;
layout(push_constant) uniform GizmoPush { vec4 cameraRight; vec4 cameraUp; vec4 cameraForward; vec4 viewportAndDpi; vec4 gizmoParams; vec4 interactionParams; } pc;
layout(location=0) in vec2 vNdc; layout(location=0) out vec4 outColor;
const int ENDPOINT_COUNT=6; const float AXIS_RADIUS_DIP=24.,HUB_RADIUS_DIP=11.,POSITIVE_RADIUS_DIP=8.5,NEGATIVE_RADIUS_DIP=7.5,HOVER_RADIUS_DIP=10.5,PRESSED_RADIUS_DIP=11.,AXIS_WIDTH_DIP=5.;
const vec3 AXIS_COLOR[3]=vec3[3](vec3(.929,.420,.420),vec3(.310,.682,.447),vec3(.435,.643,.941));
const vec3 HUB_LIGHT=vec3(.925,.945,.965),HUB_DARK=vec3(.720,.765,.810),HUB_RIM=vec3(.310,.380,.455),LABEL_COLOR=vec3(.985),LABEL_SHADOW=vec3(.120,.160,.200);
struct Endpoint{vec2 position;float depth;float radius;float alpha;int axis;int index;bool positive;bool visible;};
float aaWidth(float d,float dpi){return max(fwidth(d),.65/dpi);} float circleMask(vec2 p,vec2 c,float r,float dpi){float d=length(p-c)-r;return 1.-smoothstep(-aaWidth(d,dpi),aaWidth(d,dpi),d);} float ringMask(vec2 p,vec2 c,float r,float w,float dpi){float d=abs(length(p-c)-r)-w*.5;return 1.-smoothstep(-aaWidth(d,dpi),aaWidth(d,dpi),d);} float segmentMask(vec2 p,vec2 a,vec2 b,float w,float dpi){vec2 ab=b-a;float t=clamp(dot(p-a,ab)/max(dot(ab,ab),1e-6),0.,1.);float d=length(p-(a+ab*t))-w*.5;return 1.-smoothstep(-aaWidth(d,dpi),aaWidth(d,dpi),d);}
void compositeOver(inout vec4 a,vec3 c,float x){x=clamp(x,0.,1.);a.rgb=c*x+a.rgb*(1.-x);a.a=x+a.a*(1.-x);} vec3 axisDirection(int i){if(i==0)return vec3(1,0,0);if(i==1)return vec3(-1,0,0);if(i==2)return vec3(0,1,0);if(i==3)return vec3(0,-1,0);if(i==4)return vec3(0,0,1);return vec3(0,0,-1);} vec2 fallbackProjection(int i){if(i==0)return vec2(1,0);if(i==1)return vec2(-1,0);if(i==2)return vec2(.75,.66);if(i==3)return vec2(-.75,-.66);if(i==4)return vec2(0,-1);return vec2(0,1);}
Endpoint buildEndpoint(int i,vec2 c,vec3 right,vec3 up,vec3 forward){vec3 d=axisDirection(i);vec2 q=vec2(dot(d,right),-dot(d,up));bool positive=(i%2)==0;float depth=-dot(d,forward),front=clamp((depth+1.)*.5,0.,1.);if(length(q)<.2)q=depth>0.?vec2(0):fallbackProjection(i);Endpoint e;e.position=depth>.0&&length(q)<.2?c:c+normalize(q)*AXIS_RADIUS_DIP;e.depth=depth;e.radius=positive?POSITIVE_RADIUS_DIP:NEGATIVE_RADIUS_DIP;e.alpha=positive?.55+.45*front:.40+.38*front;e.axis=i/2;e.index=i;e.positive=positive;e.visible=true;return e;}
float glyphX(vec2 p,vec2 c,float d){float s=3.;return max(segmentMask(p,c+vec2(-s,-s),c+vec2(s,s),1.15,d),segmentMask(p,c+vec2(-s,s),c+vec2(s,-s),1.15,d));} float glyphY(vec2 p,vec2 c,float d){float s=3.2;return max(max(segmentMask(p,c+vec2(-s,-s),c,1.15,d),segmentMask(p,c+vec2(s,-s),c,1.15,d)),segmentMask(p,c,c+vec2(0,s),1.15,d));} float glyphZ(vec2 p,vec2 c,float d){float x=3.,y=3.;return max(max(segmentMask(p,c+vec2(-x,-y),c+vec2(x,-y),1.15,d),segmentMask(p,c+vec2(x,-y),c+vec2(-x,y),1.15,d)),segmentMask(p,c+vec2(-x,y),c+vec2(x,y),1.15,d));} float glyph(vec2 p,vec2 c,int a,float d){if(a==0)return glyphX(p,c,d);if(a==1)return glyphY(p,c,d);return glyphZ(p,c,d);}
void drawAxis(inout vec4 a,vec2 p,vec2 c,Endpoint e,float dpi){vec2 v=e.position-c;float l=length(v);if(l<1e-4)return;vec2 d=v/l;float x=segmentMask(p,c+d*(HUB_RADIUS_DIP+1.6),e.position-d*(e.radius+1.4),AXIS_WIDTH_DIP,dpi);compositeOver(a,AXIS_COLOR[e.axis],x*e.alpha*.78);} void drawEndpoint(inout vec4 a,vec2 p,Endpoint e,float dpi){vec3 c=AXIS_COLOR[e.axis];if(!e.positive)c=mix(vec3(.58,.62,.66),c,.45);compositeOver(a,c,circleMask(p,e.position,e.radius,dpi)*e.alpha);compositeOver(a,mix(c,vec3(.14),.36),ringMask(p,e.position,e.radius-.45,.8,dpi)*e.alpha*.55);}
float glyphMinus(vec2 p,vec2 c,float d){return segmentMask(p,c+vec2(-2.2,0),c+vec2(2.2,0),1.1,d);}
void drawLabel(inout vec4 a,vec2 p,Endpoint e,float dpi){if(!e.visible||e.depth<=0.)return;vec2 c=e.positive?e.position:e.position+vec2(2.0,0);if(!e.positive){compositeOver(a,LABEL_SHADOW,glyphMinus(p,e.position-vec2(2.5,.75),dpi)*.52);compositeOver(a,LABEL_COLOR,glyphMinus(p,e.position-vec2(2.5,0),dpi)*.96);}compositeOver(a,LABEL_SHADOW,glyph(p,c+vec2(.65,.75),e.axis,dpi)*.52);compositeOver(a,LABEL_COLOR,glyph(p,c,e.axis,dpi)*.96);}
void main(){float dpi=max(pc.gizmoParams.w,.5),sizeDip=pc.gizmoParams.x,marginDip=pc.gizmoParams.y;vec2 vp=pc.viewportAndDpi.xy,tl=vec2(vp.x-marginDip*dpi-sizeDip*dpi,marginDip*dpi),p=(gl_FragCoord.xy-tl)/dpi;if(any(lessThan(p,vec2(0)))||any(greaterThan(p,vec2(sizeDip))))discard;vec2 center=vec2(sizeDip*.5);vec3 right=normalize(pc.cameraRight.xyz),up=normalize(pc.cameraUp.xyz),forward=normalize(pc.cameraForward.xyz);Endpoint e[ENDPOINT_COUNT];for(int i=0;i<ENDPOINT_COUNT;i++)e[i]=buildEndpoint(i,center,right,up,forward);int order[ENDPOINT_COUNT];for(int i=0;i<ENDPOINT_COUNT;i++)order[i]=i;for(int i=1;i<ENDPOINT_COUNT;i++){int k=order[i],j=i-1;while(j>=0&&e[order[j]].depth>e[k].depth){order[j+1]=order[j];j--;}order[j+1]=k;}vec4 acc=vec4(0);for(int i=0;i<ENDPOINT_COUNT;i++){drawAxis(acc,p,center,e[order[i]],dpi);drawEndpoint(acc,p,e[order[i]],dpi);}float hub=circleMask(p,center,HUB_RADIUS_DIP,dpi),hd=clamp(length(p-center)/HUB_RADIUS_DIP,0.,1.);compositeOver(acc,mix(HUB_LIGHT,HUB_DARK,smoothstep(.18,1.,hd)),hub*.96);compositeOver(acc,HUB_RIM,ringMask(p,center,HUB_RADIUS_DIP,1.1,dpi)*.88);compositeOver(acc,vec3(1),circleMask(p,center+vec2(-2.8,-3.1),2.15,dpi)*.20);compositeOver(acc,vec3(.54,.63,.68),circleMask(p,center,4.,dpi)*.92);for(int i=0;i<ENDPOINT_COUNT;i++)drawLabel(acc,p,e[order[i]],dpi);int hover=int(round(pc.gizmoParams.z)),active=int(round(pc.interactionParams.x)),pressed=int(round(pc.interactionParams.y));if(hover>=0&&hover<ENDPOINT_COUNT)compositeOver(acc,vec3(.98),ringMask(p,e[hover].position,HOVER_RADIUS_DIP,1.35,dpi)*.92);if(active>=0&&active<ENDPOINT_COUNT)compositeOver(acc,vec3(1,.92,.62),ringMask(p,e[active].position,e[active].radius+2.4,1.15,dpi)*.78);if(pressed>=0&&pressed<ENDPOINT_COUNT)compositeOver(acc,vec3(.72,.22,.22),ringMask(p,e[pressed].position,PRESSED_RADIUS_DIP,1.8,dpi)*.95);if(pc.interactionParams.z>.5)compositeOver(acc,vec3(1),ringMask(p,center,HUB_RADIUS_DIP+2.,1.5,dpi)*.9);if(acc.a<=.001)discard;outColor=vec4(acc.rgb/max(acc.a,1e-5),acc.a);}
