// FAR-VIEW-A: AUTO-GENERATED by ShaderBytecode.Frag.Generate.ps1 from scene.frag with glslc -O.
// SPIR-V magic: 0x07230203u
// SPIR-V SHA-256: 2665947CF40C8C1159046A8ACEAAAB3EC7066DE28A6A813B7297CAF133F31552
// Fixed block size: 256 uints; fixed line size: 16 uints.
namespace XuanYu.Render.Vulkan.Pipeline;

internal static class ShaderBytecodeFrag
{
    internal static readonly uint[] Code =
    [
        .. ShaderBytecodeFragPart01.Code,
        .. ShaderBytecodeFragPart02.Code,
        .. ShaderBytecodeFragPart03.Code,
        .. ShaderBytecodeFragPart04.Code,
        .. ShaderBytecodeFragPart05.Code,
        .. ShaderBytecodeFragPart06.Code,
        .. ShaderBytecodeFragPart07.Code,
    ];
}
