[CmdletBinding()]
param(
    [string]$CompilerPath = 'glslc',
    [switch]$Validate
)

$ErrorActionPreference = 'Stop'
$pipeline = $PSScriptRoot
$project = (Resolve-Path (Join-Path $pipeline '..\..')).Path
$source = Join-Path $project 'XuanYu.Render.Vulkan\Shaders\scene.frag'
$output = $pipeline
$entry = Join-Path $output 'ShaderBytecode.Frag.cs'
$blockSize = 256
$lineSize = 16

function Read-SpirvWords([string]$path) {
    $bytes = [System.IO.File]::ReadAllBytes($path)
    if (($bytes.Length % 4) -ne 0) { throw "SPIR-V byte count is not uint aligned: $($bytes.Length)" }
    $words = [System.Collections.Generic.List[uint]]::new()
    for ($i = 0; $i -lt $bytes.Length; $i += 4) { $words.Add([BitConverter]::ToUInt32($bytes, $i)) }
    return $words
}

function Format-Words($words) {
    $lines = [System.Collections.Generic.List[string]]::new()
    for ($i = 0; $i -lt $words.Count; $i += $lineSize) {
        $end = [Math]::Min($i + $lineSize, $words.Count)
        $values = for ($j = $i; $j -lt $end; $j++) { '0x{0:X8}u' -f $words[$j] }
        $lines.Add('        ' + ($values -join ', ') + ',')
    }
    return $lines
}

function New-PartText([int]$number, $words) {
    $text = [System.Collections.Generic.List[string]]::new()
    $text.Add('// AUTO-GENERATED by ShaderBytecode.Frag.Generate.ps1; fixed 256 uint block.')
    $text.Add('namespace XuanYu.Render.Vulkan.Pipeline;')
    $text.Add('')
    $text.Add("internal static class ShaderBytecodeFragPart{0:D2}" -f $number)
    $text.Add('{')
    $text.Add('    internal static readonly uint[] Code =')
    $text.Add('    [')
    foreach ($line in (Format-Words $words)) { $text.Add([string]$line) }
    $text.Add('    ];')
    $text.Add('}')
    return $text
}

$spv = [System.IO.Path]::GetTempFileName()
try {
    & $CompilerPath -O $source -o $spv
    if ($LASTEXITCODE -ne 0) { throw "glslc failed with exit code $LASTEXITCODE" }
    $words = Read-SpirvWords $spv
    $hash = (Get-FileHash -Algorithm SHA256 $spv).Hash
    $partCount = [Math]::Ceiling($words.Count / $blockSize)
    $partPaths = [System.Collections.Generic.List[string]]::new()
    for ($part = 0; $part -lt $partCount; $part++) {
        $start = $part * $blockSize
        $end = [Math]::Min($start + $blockSize, $words.Count)
        $partWords = [uint[]]$words[$start..($end - 1)]
        $path = Join-Path $output ('ShaderBytecode.Frag.Part{0:D2}.cs' -f ($part + 1))
        $partPaths.Add($path)
        if (-not $Validate) { [System.IO.File]::WriteAllLines($path, (New-PartText ($part + 1) $partWords)) }
    }

    $entryText = [System.Collections.Generic.List[string]]::new()
    $entryText.Add('// FAR-VIEW-A: AUTO-GENERATED by ShaderBytecode.Frag.Generate.ps1 from scene.frag with glslc -O.')
    $entryText.Add('// SPIR-V magic: 0x07230203u')
    $entryText.Add("// SPIR-V SHA-256: $hash")
    $entryText.Add("// Fixed block size: $blockSize uints; fixed line size: $lineSize uints.")
    $entryText.Add('namespace XuanYu.Render.Vulkan.Pipeline;')
    $entryText.Add('')
    $entryText.Add('internal static class ShaderBytecodeFrag')
    $entryText.Add('{')
    $entryText.Add('    internal static readonly uint[] Code =')
    $entryText.Add('    [')
    for ($part = 1; $part -le $partCount; $part++) { $entryText.Add("        .. ShaderBytecodeFragPart{0:D2}.Code," -f $part) }
    $entryText.Add('    ];')
    $entryText.Add('}')
    if (-not $Validate) { [System.IO.File]::WriteAllLines($entry, $entryText) }

    $allPaths = @($entry) + @($partPaths)
    $lineFailures = @($allPaths | Where-Object { (Get-Content -LiteralPath $_).Count -gt 100 })
    if ($lineFailures.Count -gt 0) { throw "Generated 5+100 violation: $($lineFailures -join ', ')" }
    if ($Validate) {
        $embedded = [System.Collections.Generic.List[uint]]::new()
        foreach ($path in $partPaths) {
            if (-not (Test-Path -LiteralPath $path)) { throw "Missing generated part: $path" }
            $text = Get-Content -Raw -LiteralPath $path
            foreach ($match in [regex]::Matches($text, '0x[0-9A-Fa-f]+u')) {
                $embedded.Add([Convert]::ToUInt32($match.Value.Substring(2, $match.Value.Length - 3), 16))
            }
        }
        if ($embedded.Count -ne $words.Count) { throw "Token count mismatch: $($embedded.Count) != $($words.Count)" }
        for ($i = 0; $i -lt $words.Count; $i++) {
            if ($embedded[$i] -ne $words[$i]) { throw "Token mismatch at index $i" }
        }
        $entryText = Get-Content -Raw -LiteralPath $entry
        if (-not $entryText.Contains("SPIR-V SHA-256: $hash")) { throw 'Entry hash mismatch' }
        'Token sequence: PASS'
    }
    "Source: $source"
    "Compiler: $CompilerPath -O"
    "Output: $entry plus $partCount deterministic parts"
    "Tokens: $($words.Count)"
    "SHA-256: $hash"
    "5+100: PASS"
    if ($Validate) { 'Mode: VALIDATE' } else { 'Mode: GENERATE' }
}
finally {
    if (Test-Path -LiteralPath $spv) { [System.IO.File]::Delete($spv) }
}
